const Songs = [
    //Eminem - https://en.wikipedia.org/wiki/Eminem_singles_discography
    //Eminem as lead artist
    { "title": "Just Don't Give a Fuck", "artists": ["Eminem"] },
    { "title": "My Name Is", "artists": ["Eminem"] },
    { "title": "Role Model", "artists": ["Eminem"] },
    { "title": "Guilty Conscience", "artists": ["Eminem", "Dr. Dre"] },
    { "title": "The Real Slim Shady", "artists": ["Eminem"] },
    { "title": "The Way I Am", "artists": ["Eminem"] },
    { "title": "Stan", "artists": ["Eminem", "Dido"] },
    { "title": "I'm Back", "artists": ["Eminem"] },
    { "title": "Bitch Please II", "artists": ["Eminem", "Dr. Dre", "Snoop Dogg", "Nate Dogg", "Xzibit"] },
    { "title": "Kill You", "artists": ["Eminem"] },
    { "title": "Hellbound", "artists": ["Eminem", "J-Black", "Masta Ace"] },
    { "title": "Without Me", "artists": ["Eminem"] },
    { "title": "Cleanin' Out My Closet", "artists": ["Eminem"] },
    { "title": "Lose Yourself", "artists": ["Eminem"] },
    { "title": "Superman", "artists": ["Eminem", "Dina Rae"] },
    { "title": "Sing For The Moment", "artists": ["Eminem"] },
    { "title": "Bussiness", "artists": ["Eminem"] },
    { "title": "One Day At A Time (Em's Version)", "artists": ["Eminem", "2Pac", "Outlawz"] },
    { "title": "Just Lose It", "artists": ["Eminem"] },
    { "title": "Encore", "artists": ["Eminem", "Dr. Dre", "50 Cent"] },
    { "title": "Like Toy Soldiers", "artists": ["Eminem"] },
    { "title": "Mockingbird", "artists": ["Eminem"] },
    { "title": "Ass Like That", "artists": ["Eminem"] },
    { "title": "When I'm Gone", "artists": ["Eminem"] },
    { "title": "Shake That", "artists": ["Eminem", "Nate Dogg"] },
    { "title": "You Don't Know", "artists": ["Eminem", "50 Cent", "Lloyd Banks", "Cashis"] },
    { "title": "Jimmy Crack Corn", "artists": ["Eminem", "50 Cent"] },
    { "title": "We Made You", "artists": ["Eminem"] },
    { "title": "3 a.m.", "artists": ["Eminem"] },
    { "title": "Old Time's Sake", "artists": ["Eminem", "Dr. Dre"] },
    { "title": "Beautiful", "artists": ["Eminem"] },
    { "title": "Not Afraid", "artists": ["Eminem"] },
    { "title": "Love The Way You Lie", "artists": ["Eminem", "Rihanna"] },
    { "title": "No Love", "artists": ["Eminem", "Lil Wayne"] },
    { "title": "Space Bound", "artists": ["Eminem"] },
    { "title": "Berzerk", "artists": ["Eminem"] },
    { "title": "Survival", "artists": ["Eminem"] },
    { "title": "Rap God", "artists": ["Eminem"] },
    { "title": "The Monster", "artists": ["Eminem", "Rihanna"] },
    { "title": "Headlights", "artists": ["Eminem", "Nate Ruess"] },
    { "title": "Guts Over Fear", "artists": ["Eminem", "Sia"] },
    { "title": "Detroit vs. Everybody", "artists": ["Eminem", "Royce da 5'9\"", "Big Sean", "Danny Brown", "DeJ Loaf", "Trick-Trick"] },
    { "title": "Phenomenal", "artists": ["Eminem"] },
    { "title": "Kings Never Die", "artists": ["Eminem", "Gwen Stefani"] },
    { "title": "Walk On Water", "artists": ["Eminem", "Beyonce"] },
    { "title": "River", "artists": ["Eminem", "Ed Sheeran"] },
    { "title": "Nowhere Fast", "artists": ["Eminem", "Kehlani"] },
    { "title": "Remind Me", "artists": ["Eminem"] },
    { "title": "Fall", "artists": ["Eminem"] },
    { "title": "Killshot", "artists": ["Eminem"] },
    { "title": "Venom", "artists": ["Eminem"] },
    { "title": "Lucky You", "artists": ["Eminem", "Joyner Lucas"] },
    { "title": "Darkness", "artists": ["Eminem"] },
    { "title": "Godzilla", "artists": ["Eminem", "Juice Wrld"] },
    { "title": "The Adventures Of Moon Man & Slim Shady", "artists": ["Eminem", "Kid Cudi"] },
    { "title": "Those Kinda Nights", "artists": ["Eminem", "Ed Sheeran"] },
    { "title": "The King And I", "artists": ["Eminem", "CeeLo Green"] },
    { "title": "From The D 2 The LBC", "artists": ["Eminem", "Snoop Dogg"] },
    { "title": "Lace It", "artists": ["Eminem", "Juice Wrld", "Benny Blanco"] },
    //Eminem as featured artist
    { "title": "Dead Wrong", "artists": ["Eminem", "The Notorious B.I.G."] },
    { "title": "Forgot About Dre", "artists": ["Eminem", "Dr. Dre"] },
    { "title": "Rock City", "artists": ["Eminem", "Royce da 5'9\""] },
    { "title": "Welcome 2 Detroit", "artists": ["Eminem", "Trick Trick"] },
    { "title": "Smack That", "artists": ["Eminem", "Akon"] },
    { "title": "Forever", "artists": ["Eminem", "Drake, Kanye West", "Lil Wayne"] },
    { "title": "Drop the World", "artists": ["Eminem", "Lil Wayne"] },
    { "title": "Airplanes, Part II", "artists": ["Eminem", "B.o.B", "Hayley Williams"] },
    { "title": "That's All She Wrote", "artists": ["Eminem", "T.I."] },
    { "title": "I Need a Doctor", "artists": ["Eminem", "Dr. Dre", "Skylar Grey"] },
    { "title": "Writer's Block", "artists": ["Eminem", "Royce da 5'9\""] },
    { "title": "Throw That", "artists": ["Eminem", "Slaughterhouse"] },
    { "title": "Our House", "artists": ["Eminem", "Slaughterhouse", "Skylar Grey"] },
    { "title": "My Life", "artists": ["Eminem", "50 Cent", "Adam levine"] },
    { "title": "C'mon Let Me Ride", "artists": ["Eminem", "Skylar Grey"] },
    { "title": "Calm Down", "artists": ["Eminem", "Busta Rhymes"] },
    { "title": "Twerk Dat Pop That", "artists": ["Eminem", "Trick Trick", "Royce da 5'9\""] },
    { "title": "Best Friend", "artists": ["Eminem", "Yelawolf"] },
    { "title": "Revenge", "artists": ["Eminem", "Pink"] },
    { "title": "Caterpillar", "artists": ["Eminem", "Royce da 5'9\"", "King Green"] },
    { "title": "Homicide", "artists": ["Eminem", "Logic"] },
    { "title": "Last One Standing", "artists": ["Eminem", "Skylar Grey", "Polo G", "Mozzy"] },
    { "title": "Realest", "artists": ["Eminem", "Ez Mil"] },
    //Eminem Promotional singles
    //Eminem other charted and certified songs
    //Rihanna - https://en.wikipedia.org/wiki/Rihanna_singles_discography
    //Rihanna as lead artist
    { "title": "Pon de Replay", "artists": ["Rihanna"] },
    { "title": "If It's Lovin' That You Want", "artists": ["Rihanna"] },
    { "title": "SOS", "artists": ["Rihanna"] },
    { "title": "Unfaithful", "artists": ["Rihanna"] },
    { "title": "We Ride", "artists": ["Rihanna"] },
    { "title": "Break It Off", "artists": ["Rihanna", "Sean Paul"] },
    { "title": "Umbrella", "artists": ["Rihanna", "Jay-Z"] },
    { "title": "Shut Up and Drive", "artists": ["Rihanna"] },
    { "title": "Hate That I Love You", "artists": ["Rihanna", "Ne-Yo"] },
    { "title": "Don't Stop the Music", "artists": ["Rihanna"] },
    { "title": "Take a Bow", "artists": ["Rihanna"] },
    { "title": "Disturbia", "artists": ["Rihanna"] },
    { "title": "Rehab", "artists": ["Rihanna"] },
    { "title": "Russian Roulette", "artists": ["Rihanna"] },
    { "title": "Hard", "artists": ["Rihanna", "Jeezy"] },
    { "title": "Wait Your Turn", "artists": ["Rihanna"] },
    { "title": "Rude Boy", "artists": ["Rihanna"] },
    { "title": "Te Amo", "artists": ["Rihanna"] },
    { "title": "Rockstar 101", "artists": ["Rihanna", "Slash"] },
    { "title": "Only Girl (In the World)", "artists": ["Rihanna"] },
    { "title": "What's My Name?", "artists": ["Rihanna", "Drake"] },
    { "title": "Raining Men", "artists": ["Rihanna", "Nicki Minaj"] },
    { "title": "S&M", "artists": ["Rihanna"] },
    { "title": "California King Bed", "artists": ["Rihanna"] },
    { "title": "Man Down", "artists": ["Rihanna"] },
    { "title": "Cheers (Drink to That)", "artists": ["Rihanna"] },
    { "title": "We Found Love", "artists": ["Rihanna", "Calvin Harris"] },
    { "title": "You da One", "artists": ["Rihanna"] },
    { "title": "Talk That Talk", "artists": ["Rihanna", "Jay-Z"] },
    { "title": "Princess of China", "artists": ["Rihanna", "Coldplay"] },
    { "title": "Where Have You Been", "artists": ["Rihanna"] },
    { "title": "Diamonds", "artists": ["Rihanna"] },
    { "title": "Stay", "artists": ["Rihanna", "Mikky Ekko"] },
    { "title": "Pour It Up", "artists": ["Rihanna"] },
    { "title": "Right Now", "artists": ["Rihanna", "David Guetta"] },
    { "title": "What Now", "artists": ["Rihanna"] },
    { "title": "Jump", "artists": ["Rihanna"] },
    { "title": "FourFiveSeconds", "artists": ["Rihanna", "Kanye West", "Paul McCartney"] },
    { "title": "Towards the Sun", "artists": ["Rihanna"] },
    { "title": "Bitch Better Have My Money", "artists": ["Rihanna"] },
    { "title": "American Oxygen", "artists": ["Rihanna"] },
    { "title": "Work", "artists": ["Rihanna", "Drake"] },
    { "title": "Kiss It Better", "artists": ["Rihanna"] },
    { "title": "Needed Me", "artists": ["Rihanna"] },
    { "title": "Nothing Is Promised", "artists": ["Rihanna", "Mike WiLL Made-It"] },
    { "title": "Sledgehammer", "artists": ["Rihanna"] },
    { "title": "Love on the Brain", "artists": ["Rihanna"] },
    { "title": "Lemon", "artists": ["Rihanna", "N.E.R.D."] },
    { "title": "Believe It", "artists": ["Rihanna", "PartyNextDoor"] },
    { "title": "Lift Me Up", "artists": ["Rihanna"] },
    //Rihanna as featured artist
    { "title": "Roll It", "artists": ["Rihanna", "J-Status", "Shontelle"] },
    { "title": "If I Never See Your Face Again", "artists": ["Rihanna", "Maroon 5"] },
    { "title": "Live Your Life", "artists": ["Rihanna", "T.I."] },
    { "title": "Numba 1 (Tide Is High)", "artists": ["Rihanna", "Kardinal Offishall"] },
    { "title": "Run This Town", "artists": ["Rihanna", "Jay-Z", "Kanye West"] },
    { "title": "Love The Way You Lie", "artists": ["Rihanna", "Eminem"] },
    { "title": "Who's That Chick?", "artists": ["Rihanna", "David Guetta"] },
    { "title": "All of the Lights", "artists": ["Rihanna", "Kanye West", "Kid Cudi"] },
    { "title": "Fly", "artists": ["Rihanna", "Nicki Minaj"] },
    { "title": "Take Care", "artists": ["Rihanna", "Drake"] },
    { "title": "The Monster", "artists": ["Rihanna", "Eminem"] },
    { "title": "Can't Remember to Forget You", "artists": ["Rihanna", "Shakira"] },
    { "title": "This Is What You Came For", "artists": ["Rihanna", "Calvin Harris"] },
    { "title": "Too Good", "artists": ["Rihanna", "Drake"] },
    { "title": "Selfish", "artists": ["Rihanna", "Future"] },
    { "title": "Wild Thoughts", "artists": ["Rihanna", "DJ Khaled", "Bryson Tiller"] },
    { "title": "Loyalty", "artists": ["Rihanna", "Kendrick Lamar"] },
    //Charity singles
    //Promotional singles
    //Other charted and certified songs
    //Jay-Z - https://en.wikipedia.org/wiki/Jay-Z_singles_discography
    //Jay-Z as lead artist
    { "title": "In My Lifetime", "artists": ["Jay-Z"] },
    { "title": "Dead Presidents", "artists": ["Jay-Z"] },
    { "title": "Ain't No Nigga", "artists": ["Jay-Z", "Foxy Brown"] },
    { "title": "Can't Knock the Hustle", "artists": ["Jay-Z", "Mary J.", "Blige"] },
    { "title": "Feelin' It", "artists": ["Jay-Z"] },
    { "title": "Who You Wit", "artists": ["Jay-Z"] },
    { "title": "(Always Be My) Sunshine", "artists": ["Jay-Z", "Babyface", "Foxy Brown"] },
    { "title": "Wishing on a Star", "artists": ["Jay-Z", "Gwen Dickey"] },
    { "title": "The City Is Mine", "artists": ["Jay-Z", "Blackstreet"] },
    { "title": "It's Alright", "artists": ["Jay-Z", "Memphis Bleek"] },
    { "title": "Can I Get A...", "artists": ["Jay-Z", "Ja Rule, Amil"] },
    { "title": "Hard Knock Life (Ghetto Anthem)", "artists": ["Jay-Z"] },
    { "title": "Money, Cash, Hoes", "artists": ["Jay-Z", "DMX"] },
    { "title": "Nigga What, Nigga Who (Originator 99)", "artists": ["Jay-Z", "Amil", "Big Jaz"] },
    { "title": "Jigga My Nigga", "artists": ["Jay-Z"] },
    { "title": "Girl's Best Friend", "artists": ["Jay-Z"] },
    { "title": "Do It Again (Put Ya Hands Up)", "artists": ["Jay-Z", "Amil", "Beanie Sigel"] },
    { "title": "Things That U Do", "artists": ["Jay-Z", "Mariah Carey"] },
    { "title": "Anything", "artists": ["Jay-Z"] },
    { "title": "Big Pimpin'", "artists": ["Jay-Z", "UGK"] },
    { "title": "Hey Papi", "artists": ["Jay-Z", "Amil", "Memphis Bleek"] },
    { "title": "I Just Wanna Love U (Give It 2 Me)", "artists": ["Jay-Z"] },
    { "title": "Change the Game", "artists": ["Jay-Z", "Beanie Sigel", "Memphis Bleek"] },
    { "title": "Guilty Until Proven Innocent", "artists": ["Jay-Z", "R. Kelly"] },
    { "title": "Izzo (H.O.V.A.)", "artists": ["Jay-Z"] },
    { "title": "Girls, Girls, Girls", "artists": ["Jay-Z"] },
    { "title": "Jigga That Nigga", "artists": ["Jay-Z"] },
    { "title": "Song Cry", "artists": ["Jay-Z"] },
    { "title": "'03 Bonnie & Clyde", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "Hovi Baby", "artists": ["Jay-Z"] },
    { "title": "Excuse Me Miss", "artists": ["Jay-Z"] },
    { "title": "La La La", "artists": ["Jay-Z"] },
    { "title": "Change Clothes", "artists": ["Jay-Z"] },
    { "title": "Dirt Off Your Shoulder", "artists": ["Jay-Z"] },
    { "title": "99 Problems", "artists": ["Jay-Z"] },
    { "title": "Big Chips", "artists": ["Jay-Z", "R. Kelly"] },
    { "title": "Don't Let Me Die", "artists": ["Jay-Z", "R. Kelly"] },
    { "title": "Numb/Encore", "artists": ["Jay-Z", "Linkin Park"] },
    { "title": "Show Me What You Got", "artists": ["Jay-Z"] },
    { "title": "Lost One", "artists": ["Jay-Z", "Chrisette Michele"] },
    { "title": "30 Something", "artists": ["Jay-Z"] },
    { "title": "Hollywood", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "Blue Magic", "artists": ["Jay-Z", "Pharrell Williams", "En Vogue"] },
    { "title": "Roc Boys (And the Winner Is)...", "artists": ["Jay-Z"] },
    { "title": "I Know", "artists": ["Jay-Z", "Pharrell Williams"] },
    { "title": "Swagga Like Us", "artists": ["Jay-Z", "T.I.", "Lil Wayne", "Kanye West"] },
    { "title": "Jockin' Jay-Z (Dopeboy Fresh)", "artists": ["Jay-Z"] },
    { "title": "D.O.A. (Death of Auto-Tune)", "artists": ["Jay-Z"] },
    { "title": "Run This Town", "artists": ["Jay-Z", "Kanye West", "Rihanna"] },
    { "title": "Empire State of Mind", "artists": ["Jay-Z", "Alicia Keys"] },
    { "title": "On to the Next One", "artists": ["Jay-Z", "Swizz Beatz"] },
    { "title": "Young Forever", "artists": ["Jay-Z", "Mr Hudson"] },
    { "title": "A Star Is Born", "artists": ["Jay-Z", "J. Cole"] },
    { "title": "H.A.M", "artists": ["Jay-Z", "Kanye West"] },
    { "title": "Otis", "artists": ["Jay-Z", "Kanye West", "Otis Redding"] },
    { "title": "Niggas in Paris", "artists": ["Jay-Z", "Kanye West"] },
    { "title": "Why I Love You", "artists": ["Jay-Z", "Kanye West", "Mr Hudson"] },
    { "title": "Gotta Have It", "artists": ["Jay-Z", "Kanye West"] },
    { "title": "Glory", "artists": ["Jay-Z", "B.I.C."] },
    { "title": "No Church in the Wild", "artists": ["Jay-Z", "Kanye West", "Frank Ocean"] },
    { "title": "Clique", "artists": ["Jay-Z", "Kanye West", "Big Sean"] },
    { "title": "Holy Grail", "artists": ["Jay-Z", "Justin Timberlake"] },
    { "title": "Tom Ford", "artists": ["Jay-Z"] },
    { "title": "Part II (On the Run)", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "4:44", "artists": ["Jay-Z"] },
    { "title": "Bam", "artists": ["Jay-Z", "Damian Marley"] },
    { "title": "Family Feud", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "What It Feels Like", "artists": ["Jay-Z", "Nipsey Hussle"] },
    { "title": "Guns Go Bang", "artists": ["Jay-Z", "Kid Cudi"] },
    { "title": "I Want You Forever", "artists": ["Jay-Z", "Jeymes Samuel", "D'Angelo"] },
    //Jay-Z as featured artist
    { "title": "Hawaiian Sophie", "artists": ["Jay-Z", "The Jaz"] },
    { "title": "The Originators", "artists": ["Jay-Z", "The Jaz"] },
    { "title": "Show & Prove", "artists": ["Jay-Z", "Big Daddy Kane", "Big Scoob", "Sauce Money", "Shyheim", "Ol' Dirty Bastard"] },
    { "title": "I'll Be", "artists": ["Jay-Z", "Foxy Brown"] },
    { "title": "All of My Days", "artists": ["Jay-Z", "Changing Faces", "R. Kelly"] },
    { "title": "Love for Free", "artists": ["Jay-Z", "Rell"] },
    { "title": "Money Ain't a Thang", "artists": ["Jay-Z", "Jermaine Dupri"] },
    { "title": "4 Alarm Blaze", "artists": ["Jay-Z", "M.O.P.", "Teflon"] },
    { "title": "Lobster & Scrimp", "artists": ["Jay-Z", "Timbaland"] },
    { "title": "Heartbreaker", "artists": ["Jay-Z", "Mariah Carey"] },
    { "title": "What You Think of That", "artists": ["Jay-Z", "Memphis Bleek"] },
    { "title": "Do You Like It... Do You Want It...", "artists": ["Jay-Z", "Puff Daddy"] },
    { "title": "4 da Fam", "artists": ["Jay-Z", "Amil", "Beanie Sigel", "Memphis Bleek"] },
    { "title": "Best of Me Part II", "artists": ["Jay-Z", "Mýa"] },
    { "title": "Is That Your Chick (The Lost Verses)", "artists": ["Jay-Z", "Memphis Bleek", "Twista", "Missy Elliott"] },
    { "title": "Mi Amor", "artists": ["Jay-Z", "Angie Martinez"] },
    { "title": "Do My...", "artists": ["Jay-Z", "Memphis Bleek"] },
    { "title": "Let's Go!", "artists": ["Jay-Z", "Jaz-O", "Dibiase"] },
    { "title": "Guess Who's Back", "artists": ["Jay-Z", "Scarface", "Beanie Sigel"] },
    { "title": "It's Obvious", "artists": ["Jay-Z", "Rell"] },
    { "title": "What We Do", "artists": ["Jay-Z", "Freeway", "Beanie Sigel"] },
    { "title": "Beware of the Boys (Mundian To Bach Ke)", "artists": ["Jay-Z", "Panjabi MC"] },
    { "title": "Back in the Day", "artists": ["Jay-Z", "Missy Elliott"] },
    { "title": "Crazy in Love", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "Frontin'", "artists": ["Jay-Z", "Pharrell Williams"] },
    { "title": "Storm", "artists": ["Jay-Z", "Lenny Kravitz"] },
    { "title": "Dear Summer", "artists": ["Jay-Z", "Memphis Bleek"] },
    { "title": "Go Crazy", "artists": ["Jay-Z", "Young Jeezy"] },
    { "title": "Get Throwed", "artists": ["Jay-Z", "Bun B", "Pimp C", "Young Jeezy", "Z-Ro"] },
    { "title": "Déjà Vu", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "Umbrella", "artists": ["Jay-Z", "Rihanna"] },
    { "title": "Roc-A-Fella Billionaires", "artists": ["Jay-Z", "Freeway"] },
    { "title": "I Wanna Rock (The Kings' G-Mix)", "artists": ["Jay-Z", "Snoop Dogg"] },
    { "title": "Hot Tottie", "artists": ["Jay-Z", "USHER"] },
    { "title": "Monster", "artists": ["Jay-Z", "Kanye West", "Rick Ross", "Bon Iver", "Nicki Minaj"] },
    { "title": "I Do", "artists": ["Jay-Z", "Young Jeezy", "André 3000"] },
    { "title": "Talk That Talk", "artists": ["Jay-Z", "Rihanna"] },
    { "title": "Suit & Tie", "artists": ["Jay-Z", "Justin Timberlake"] },
    { "title": "Pound Cake / Paris Morton Music 2", "artists": ["Jay-Z", "Drake"] },
    { "title": "Drunk in Love", "artists": ["Jay-Z", "Beyonce"] },
    { "title": "The Devil Is a Lie", "artists": ["Jay-Z", "Rick Ross"] },
    { "title": "They Don't Love You No More", "artists": ["Jay-Z", "DJ Khaled", "Meek Mill", "Rick Ross", "French Montana"] },
    { "title": "Seen It All", "artists": ["Jay-Z", "Jeezy"] },
    { "title": "Pop Style", "artists": ["Jay-Z", "Drake", "Kanye West"] },
    { "title": "Drug Dealers Anonymous", "artists": ["Jay-Z", "Pusha T"] },
    { "title": "I Got the Keys", "artists": ["Jay-Z", "DJ Khaled", "Future"] },
    { "title": "Shining", "artists": ["Jay-Z", "DJ Khaled", "Beyonce"] },
    { "title": "Top Off", "artists": ["Jay-Z", "DJ Khaled", "Future", "Beyonce"] },
    { "title": "Entrepreneur", "artists": ["Jay-Z", "Pharrell Williams"] },
    { "title": "Neck & Wrist", "artists": ["Jay-Z", "Pusha T", "Pharrell Williams"] },
    //Promotional singles
    //Other charted and certified songs
    //Kanye West - https://en.wikipedia.org/wiki/Kanye_West_singles_discography
    //Kanye West as lead artist
    { "title": "Through the Wire", "artists": ["Kanye West"] },
    { "title": "All Falls Down", "artists": ["Kanye West", "Syleena Johnson"] },
    { "title": "Jesus Walks", "artists": ["Kanye West"] },
    { "title": "The New Workout Plan", "artists": ["Kanye West"] },
    { "title": "Diamonds from Sierra Leone", "artists": ["Kanye West"] },
    { "title": "Gold Digger", "artists": ["Kanye West", "Jamie Foxx"] },
    { "title": "Heard 'Em Say", "artists": ["Kanye West", "Adam Levine"] },
    { "title": "Touch the Sky", "artists": ["Kanye West", "Lupe Fiasco"] },
    { "title": "Impossible", "artists": ["Kanye West", "Twista", "Keyshia Cole", "BJ"] },
    { "title": "Drive Slow", "artists": ["Kanye West", "Paul Wall", "GLC"] },
    { "title": "Classic (Better Than I've Ever Been)", "artists": ["Kanye West", "KRS-One", "Nas", "Rakim"] },
    { "title": "Can't Tell Me Nothing", "artists": ["Kanye West"] },
    { "title": "Stronger", "artists": ["Kanye West"] },
    { "title": "Good Life", "artists": ["Kanye West", "T-Pain"] },
    { "title": "Flashing Lights", "artists": ["Kanye West", "Dwele"] },
    { "title": "Homecoming", "artists": ["Kanye West", "Chris Martin"] },
    { "title": "Love Lockdown", "artists": ["Kanye West"] },
    { "title": "Heartless", "artists": ["Kanye West"] },
    { "title": "Amazing", "artists": ["Kanye West", "Young Jeezy"] },
    { "title": "Paranoid", "artists": ["Kanye West", "Mr Hudson"] },
    { "title": "Forever", "artists": ["Kanye West", "Drake", "Lil Wayne", "Eminem"] },
    { "title": "Power", "artists": ["Kanye West"] },
    { "title": "Runaway", "artists": ["Kanye West", "Pusha T"] },
    { "title": "Monster", "artists": ["Kanye West", "Jay-Z", "Rick Ross", "Nicki Minaj", "Bon Iver"] },
    { "title": "All of the Lights", "artists": ["Kanye West", "Kid Cudi"] },
    { "title": "Christmas in Harlem", "artists": ["Kanye West", "Cyhi the Prynce", "Teyana Taylor"] },
    { "title": "H•A•M", "artists": ["Kanye West", "Jay-Z"] },
    { "title": "Otis", "artists": ["Kanye West", "Jay-Z", "Otis Redding"] },
    { "title": "Lift Off", "artists": ["Kanye West", "Jay-Z", "Beyonce"] },
    { "title": "Niggas in Paris", "artists": ["Kanye West", "Jay-Z"] },
    { "title": "Why I Love You", "artists": ["Kanye West", "Jay-Z", "Mr Hudson"] },
    { "title": "Gotta Have It", "artists": ["Kanye West", "Jay-Z"] },
    { "title": "No Church in the Wild", "artists": ["Kanye West", "Jay-Z", "Frank Ocean"] },
    { "title": "Mercy", "artists": ["Kanye West", "Big Sean", "Pusha T", "2 Chainz"] },
    { "title": "Cold", "artists": ["Kanye West", "DJ Khaled"] },
    { "title": "New God Flow", "artists": ["Kanye West", "Pusha T"] },
    { "title": "Clique", "artists": ["Kanye West", "Jay-Z", "Big Sean"] },
    { "title": "Black Skinhead", "artists": ["Kanye West"] },
    { "title": "Bound 2", "artists": ["Kanye West"] },
    { "title": "Only One", "artists": ["Kanye West", "Paul McCartney"] },
    { "title": "FourFiveSeconds", "artists": ["Kanye West", "Rihanna", "Paul McCartney"] },
    { "title": "All Day", "artists": ["Kanye West", "Theophilus London", "Allan Kingdom", "Paul McCartney"] },
    { "title": "Famous", "artists": ["Kanye West"] },
    { "title": "Father Stretch My Hands, Pt. 1", "artists": ["Kanye West"] },
    { "title": "Pt. 2", "artists": ["Kanye West"] },
    { "title": "Champions", "artists": ["Kanye West", "Gucci Mane", "Big Sean", "2 Chainz", "Travis Scott", "Yo Gotti", "Quavo", "Desiigner"] },
    { "title": "Fade", "artists": ["Kanye West"] },
    { "title": "Lift Yourself", "artists": ["Kanye West"] },
    { "title": "Ye vs. the People", "artists": ["Kanye West", "T.I."] },
    { "title": "Yikes", "artists": ["Kanye West"] },
    { "title": "All Mine", "artists": ["Kanye West"] },
    { "title": "XTCY", "artists": ["Kanye West"] },
    { "title": "I Love It", "artists": ["Kanye West", "Lil Pump"] },
    { "title": "Follow God", "artists": ["Kanye West"] },
    { "title": "Closed on Sunday", "artists": ["Kanye West"] },
    { "title": "Wash Us in the Blood", "artists": ["Kanye West", "Travis Scott"] },
    { "title": "Nah Nah Nah", "artists": ["Kanye West"] },
    { "title": "Hurricane", "artists": ["Kanye West", "Weeknd", "Lil Baby"] },
    { "title": "Life of the Party", "artists": ["Kanye West", "André 3000"] },
    { "title": "Believe What I Say", "artists": ["Kanye West"] },
    { "title": "Off the Grid", "artists": ["Kanye West", "Playboi Carti", "Fivio Foreign"] },
    { "title": "Eazy", "artists": ["Kanye West", "The Game"] },
    { "title": "City of Gods", "artists": ["Kanye West", "Fivio Foreign", "Alicia Keys"] },
    { "title": "True Love", "artists": ["Kanye West", "XXXTentacion"] },
    { "title": "Hot Shit", "artists": ["Kanye West", "Cardi B", "Lil Durk"] },
    //Kanye West as featured artist
    { "title": "Welcome 2 Chicago", "artists": ["Kanye West", "Abstract Mindstate"] },
    { "title": "Slow Jamz", "artists": ["Kanye West", "Twista", "Jamie Foxx"] },
    { "title": "This Way", "artists": ["Kanye West", "Dilated Peoples"] },
    { "title": "Talk About Our Love", "artists": ["Kanye West", "Brandy"] },
    { "title": "Higher", "artists": ["Kanye West", "Do or Die"] },
    { "title": "The Food", "artists": ["Kanye West", "Common", "DJ Dummy"] },
    { "title": "Selfish", "artists": ["Kanye West", "Slum Village", "John Legend"] },
    { "title": "Real Love", "artists": ["Kanye West", "Rell", "Consequence"] },
    { "title": "Down and Out", "artists": ["Kanye West", "Cam'ron", "Syleena Johnson"] },
    { "title": "The Corner", "artists": ["Kanye West", "Common", "The Last Poets"] },
    { "title": "Pusha Man", "artists": ["Kanye West", "Bump J"] },
    { "title": "Go!", "artists": ["Kanye West", "Common", "John Mayer"] },
    { "title": "Wouldn't You Like to Ride?", "artists": ["Kanye West", "Malik Yusef", "Common"] },
    { "title": "Number One", "artists": ["Kanye West", "John Legend"] },
    { "title": "Extravaganza", "artists": ["Kanye West", "Jamie Foxx"] },
    { "title": "Brand New", "artists": ["Kanye West", "Rhymefest"] },
    { "title": "Grammy Family", "artists": ["Kanye West", "DJ Khaled", "Consequence", "John Legend"] },
    { "title": "Number One", "artists": ["Kanye West", "Pharrell Williams"] },
    { "title": "Wouldn't Get Far", "artists": ["Kanye West", "The Game"] },
    { "title": "I Still Love H.E.R.", "artists": ["Kanye West", "Teriyaki Boyz"] },
    { "title": "Anything", "artists": ["Kanye West", "Patti LaBelle", "Consequence", "Mary Mary"] },
    { "title": "Pro Nails", "artists": ["Kanye West", "Kid Sister"] },
    { "title": "Finer Things", "artists": ["Kanye West", "Dj Felli Fel", "Jermaine Dupri", "Fabolous", "Ne-Yo"] },
    { "title": "American Boy", "artists": ["Kanye West", "Estelle"] },
    { "title": "Put On", "artists": ["Kanye West", "Young Jeezy"] },
    { "title": "Everybody", "artists": ["Kanye West", "Fonzworth Bentley", "André 3000"] },
    { "title": "Plastic", "artists": ["Kanye West", "Really Doe"] },
    { "title": "Stay Up! (Viagra)", "artists": ["Kanye West", "88-Keys"] },
    { "title": "Swagga Like Us", "artists": ["Kanye West", "Jay-Z", "T.I.", "Lil Wayne"] },
    { "title": "Go Hard", "artists": ["Kanye West", "DJ Khaled", "T-Pain"] },
    { "title": "What It Is", "artists": ["Kanye West", "Sophia Fresh"] },
    { "title": "The Big Screen", "artists": ["Kanye West", "GLC"] },
    { "title": "Knock You Down", "artists": ["Kanye West", "Keri Hilson", "Ne-Yo"] },
    { "title": "Kinda Like a Big Deal", "artists": ["Kanye West", "Clipse"] },
    { "title": "Walkin' on the Moon", "artists": ["Kanye West", "The-Dream"] },
    { "title": "Gifted", "artists": ["Kanye West", "N.A.S.A.", "Santigold", "Lykke Li"] },
    { "title": "Supernova", "artists": ["Kanye West", "Mr Hudson"] },
    { "title": "Maybach Music 2", "artists": ["Kanye West", "Rick Ross", "T-Pain", "Lil Wayne"] },
    { "title": "Make Her Say", "artists": ["Kanye West", "Kid Cudi", "Common"] },
    { "title": "Run This Town", "artists": ["Kanye West", "Jay-Z", "Rihanna"] },
    { "title": "Whatever U Want", "artists": ["Kanye West", "Consequence", "John Legend"] },
    { "title": "Live Fast, Die Young", "artists": ["Kanye West", "Rick Ross"] },
    { "title": "Erase Me", "artists": ["Kanye West", "Kid Cudi"] },
    { "title": "Ayyy Girl", "artists": ["Kanye West", "JYJ", "Malik Yusef"] },
    { "title": "Start It Up", "artists": ["Kanye West", "Lloyd Banks", "Ryan Leslie", "Swizz Beatz", "Fabolous"] },
    { "title": "Hurricane 2.0", "artists": ["Kanye West", "Thirty Seconds to mars"] },
    { "title": "E.T.", "artists": ["Kanye West", "Katty Perry"] },
    { "title": "Marvin & Chardonnay", "artists": ["Kanye West", "Big Sean", "Roscoe Dash"] },
    { "title": "Amen", "artists": ["Kanye West", "Pusha T", "Young Jeezy"] },
    { "title": "I Wish You Would", "artists": ["Kanye West", "DJ Khaled", "Rick Ross"] },
    { "title": "Pride N Joy", "artists": ["Kanye West", "Fat Joe", "Miguel", "Jadakiss", "Mos Doe", "DJ Khaled", "Roscoe Dash", "Busta Rhymes"] },
    { "title": "Birthday Song", "artists": ["Kanye West", "2 Chainz"] },
    { "title": "Another You", "artists": ["Kanye West", "The World Famous Tony Williams"] },
    { "title": "Scape Goat (The Fix)", "artists": ["Kanye West", "D'banj"] },
    { "title": "Thank You", "artists": ["Kanye West", "Busta Rhymes", "Lil Wayne", "Q-Tip"] },
    { "title": "I Won", "artists": ["Kanye West", "Future"] },
    { "title": "Nobody", "artists": ["Kanye West", "Chief Keef"] },
    //Other collaborations

    //Promotional singles

    //Other charted and certified songs
    //Britney Spears - https://en.wikipedia.org/wiki/Britney_Spears_discography
    //Britney Spears as lead artist
    { "title": "...Baby One More Time", "artists": ["Britney Spears"] },
    { "title": "Sometimes", "artists": ["Britney Spears"] },
    { "title": "(You Drive Me) Crazy", "artists": ["Britney Spears"] },
    { "title": "Born to Make You Happy", "artists": ["Britney Spears"] },
    { "title": "From the Bottom of My Broken Heart", "artists": ["Britney Spears"] },
    { "title": "Oops!... I Did It Again", "artists": ["Britney Spears"] },
    { "title": "Lucky", "artists": ["Britney Spears"] },
    { "title": "Stronger", "artists": ["Britney Spears"] },
    { "title": "Don't Let Me Be the Last to Know", "artists": ["Britney Spears"] },
    { "title": "I'm a Slave 4 U", "artists": ["Britney Spears"] },
    { "title": "Overprotected", "artists": ["Britney Spears"] },
    { "title": "I'm Not a Girl, Not Yet a Woman", "artists": ["Britney Spears"] },
    { "title": "I Love Rock 'n' Roll", "artists": ["Britney Spears"] },
    { "title": "Boys", "artists": ["Britney Spears", "Pharrell Williams"] },
    { "title": "Anticipating", "artists": ["Britney Spears"] },
    { "title": "Me Against the Music", "artists": ["Britney Spears", "Madonna"] },
    { "title": "Toxic", "artists": ["Britney Spears"] },
    { "title": "Everytime", "artists": ["Britney Spears"] },
    { "title": "Outrageous", "artists": ["Britney Spears"] },
    { "title": "My Prerogative", "artists": ["Britney Spears"] },
    { "title": "Do Somethin'", "artists": ["Britney Spears"] },
    { "title": "Someday (I Will Understand)", "artists": ["Britney Spears"] },
    { "title": "Gimme More", "artists": ["Britney Spears"] },
    { "title": "Piece of Me", "artists": ["Britney Spears"] },
    { "title": "Break the Ice", "artists": ["Britney Spears"] },
    { "title": "Womanizer", "artists": ["Britney Spears"] },
    { "title": "Circus", "artists": ["Britney Spears"] },
    { "title": "If U Seek Amy", "artists": ["Britney Spears"] },
    { "title": "Radar", "artists": ["Britney Spears"] },
    { "title": "3", "artists": ["Britney Spears"] },
    { "title": "Hold It Against Me", "artists": ["Britney Spears"] },
    { "title": "Till the World Ends", "artists": ["Britney Spears", "Nicki Minaj", "Kesha"] },
    { "title": "I Wanna Go", "artists": ["Britney Spears"] },
    { "title": "Criminal", "artists": ["Britney Spears"] },
    { "title": "Scream & Shout", "artists": ["Britney Spears", "will.i.am"] },
    { "title": "Ooh La La", "artists": ["Britney Spears"] },
    { "title": "Work Bitch", "artists": ["Britney Spears"] },
    { "title": "Perfume", "artists": ["Britney Spears"] },
    { "title": "Til It's Gone", "artists": ["Britney Spears"] },
    { "title": "It Should Be Easy", "artists": ["Britney Spears", "will.i.am"] },
    { "title": "Pretty Girls", "artists": ["Britney Spears", "Iggy Azalea"] },
    { "title": "Tom's Diner", "artists": ["Britney Spears", "Giorgio Moroder"] },
    { "title": "Make Me", "artists": ["Britney Spears", "G-Eazy"] },
    { "title": "Slumber Party", "artists": ["Britney Spears", "Tinashe"] },
    { "title": "Mood Ring", "artists": ["Britney Spears"] },
    { "title": "Swimming in the Stars", "artists": ["Britney Spears"] },
    { "title": "Matches", "artists": ["Britney Spears", "Backstreet Boys"] },
    { "title": "Hold Me Closer", "artists": ["Britney Spears", "Elton John"] },
    { "title": "Mind Your Business", "artists": ["Britney Spears", "will.i.am"] },
    //Promotional singles

    //Charity singles

    //Other charted songs

    //Bruno Mars - https://en.wikipedia.org/wiki/Bruno_Mars_discography
    //Bruno Mars as lead artist
    { "title": "Just the Way You Are", "artists": ["Bruno Mars"] },
    { "title": "Grenade", "artists": ["Bruno Mars"] },
    { "title": "The Lazy Song", "artists": ["Bruno Mars"] },
    { "title": "Talking to the Moon", "artists": ["Bruno Mars"] },
    { "title": "Marry You", "artists": ["Bruno Mars"] },
    { "title": "It Will Rain", "artists": ["Bruno Mars"] },
    { "title": "Count On Me", "artists": ["Bruno Mars"] },
    { "title": "Locked Out of Heaven", "artists": ["Bruno Mars"] },
    { "title": "When I Was Your Man", "artists": ["Bruno Mars"] },
    { "title": "Treasure", "artists": ["Bruno Mars"] },
    { "title": "Gorilla", "artists": ["Bruno Mars"] },
    { "title": "Young Girls", "artists": ["Bruno Mars"] },
    { "title": "24K Magic", "artists": ["Bruno Mars"] },
    { "title": "That's What I Like", "artists": ["Bruno Mars"] },
    { "title": "Versace on the Floor", "artists": ["Bruno Mars"] },
    { "title": "Chunky", "artists": ["Bruno Mars"] },
    { "title": "Finesse", "artists": ["Bruno Mars", "Cardi B"] },
    { "title": "Wake Up in the Sky", "artists": ["Bruno Mars", "Gucci Mane", "Kodak Black"] },
    { "title": "Please Me", "artists": ["Bruno Mars", "Cardi B"] },
    { "title": "Blow", "artists": ["Bruno Mars", "Ed Sheeran", "Chris Stapleton"] },
    { "title": "Leave the Door Open", "artists": ["Bruno Mars", "Anderson .Paak"] }, //as Silk Sonic
    { "title": "Skate", "artists": ["Bruno Mars", "Anderson .Paak"] }, //as Silk Sonic
    { "title": "Smokin out the Window", "artists": ["Bruno Mars", "Anderson .Paak"] }, //as Silk Sonic
    { "title": "Love's Train", "artists": ["Bruno Mars", "Anderson .Paak"] }, //as Silk Sonic
    { "title": "After Last Night", "artists": ["Bruno Mars", "Anderson .Paak", "Thundercat", "Bootsy Collins"] }, //as Silk Sonic
    //Bruno Mars as featured artist
    { "title": "Nothin' on You", "artists": ["Bruno Mars", "B.o.B"] },
    { "title": "Billionaire", "artists": ["Bruno Mars", "Travie McCoy"] },
    { "title": "Mirror", "artists": ["Bruno Mars", "Lil Wayne"] },
    { "title": "Young, Wild & Free", "artists": ["Bruno Mars", "Snoop Dogg", "Wiz, Khalifa"] },
    { "title": "Bubble Butt", "artists": ["Bruno Mars", "Major Lazer", "2 Chainz", "Tyga", "Mystic"] },
    { "title": "Uptown Funk", "artists": ["Bruno Mars", "Mark Ronson"] },
    //Promotional singles

    //Other charted songs

    //Guest appearances
    //Cardi B - https://en.wikipedia.org/wiki/Cardi_B_discography
    //Cardi B as lead artist
    { "title": "Bodak Yellow", "artists": ["Cardi B"] },
    { "title": "MotorSport", "artists": ["Cardi B", "Migos", "Nicki Minaj"] },
    { "title": "Bartier Cardi", "artists": ["Cardi B", "21 Savage"] },
    { "title": "Be Careful", "artists": ["Cardi B"] },
    { "title": "I Like It", "artists": ["Cardi B", "Bad Bunny", "J Balvin"] },
    { "title": "Ring", "artists": ["Cardi B", "Kehlani"] },
    { "title": "Money", "artists": ["Cardi B"] },
    { "title": "Please Me", "artists": ["Cardi B", "Bruno Mars"] },
    { "title": "Press", "artists": ["Cardi B"] },
    { "title": "Yes", "artists": ["Cardi B", "Fat Joe", "Anuel AA"] },
    { "title": "WAP", "artists": ["Cardi B", "Megan Thee Stallion"] },
    { "title": "Up", "artists": ["Cardi B"] },
    { "title": "Hot Shit", "artists": ["Cardi B", "Kanye West", "Lil Durk"] },
    { "title": "Tomorrow 2", "artists": ["Cardi B", "GloRilla"] },
    { "title": "Point Me 2", "artists": ["Cardi B", "FendiDa Rappa"] },
    { "title": "Jealousy", "artists": ["Cardi B", "Offset"] },
    { "title": "Bongos", "artists": ["Cardi B", "Megan Thee Stallion"] },
    //Cardi B as featured artist
    { "title": "Gimme Head Too", "artists": ["Cardi B", "J.R."] },
    { "title": "Want My Love Back", "artists": ["Cardi B", "Cashflow Harlem", "Ryan Dudley"] },
    { "title": "Island Girls", "artists": ["Cardi B", "Hood Celebrityy", "Josh X", "Young Chow"] },
    { "title": "Heaven on My Mind", "artists": ["Cardi B", "Josh X"] },
    { "title": "Right Now", "artists": ["Cardi B", "Phresher"] },
    { "title": "No Limit", "artists": ["Cardi B", "G-Eazy", "A$AP Rocky"] },
    { "title": "La Modelo", "artists": ["Cardi B", "Ozuna"] },
    { "title": "Girls", "artists": ["Cardi B", "Rita Ora", "Bebe Rexha", "Charli XCX"] },
    { "title": "Dinero", "artists": ["Cardi B", "Jennifer Lopez", "DJ Khaled"] },
    { "title": "Girls Like You", "artists": ["Cardi B", "Maroon 5"] },
    { "title": "Who Want the Smoke?", "artists": ["Cardi B", "Lil Yachty", "Offset"] },
    { "title": "Backin' It Up", "artists": ["Cardi B", "Pardison", "Fontaine"] },
    { "title": "Taki Taki", "artists": ["Cardi B", "DJ Snake", "Ozuna", "Selena Gomez"] },
    { "title": "Mi Mami", "artists": ["Cardi B", "El Alfa"] },
    { "title": "Twerk", "artists": ["Cardi B", "City Girls"] },
    { "title": "Clout", "artists": ["Cardi B", "Offset"] },
    { "title": "South of the Border", "artists": ["Cardi B", "Ed Sheeran", "Camila Cabello"] },
    { "title": "Writing on the Wall", "artists": ["Cardi B", "French Montana", "Post Malone", "Rvssian"] },
    { "title": "Me Gusta", "artists": ["Cardi B", "Anitta", "Myke Towers"] },
    { "title": "Wild Side", "artists": ["Cardi B", "Normani"] },
    { "title": "Rumors", "artists": ["Cardi B", "Lizzo"] },
    { "title": "Shake It", "artists": ["Cardi B", "Kay Flock", "Dougie B", "Bory300"] },
    { "title": "Put It on da Floor Again", "artists": ["Cardi B", "Latto"] },
    //Promotional singles

    //Other charted songs

    //Guest appearances

    //Nicki Minaj - https://en.wikipedia.org/wiki/Nicki_Minaj_discography
    //Nicki Minaj as lead artist
    { "title": "Massive Attack", "artists": ["Nicki Minaj", "Sean Garrett"] },
    { "title": "Your Love", "artists": ["Nicki Minaj"] },
    { "title": "Check It Out", "artists": ["Nicki Minaj", "will.i.am"] },
    { "title": "Right Thru Me", "artists": ["Nicki Minaj"] },
    { "title": "Moment 4 Life", "artists": ["Nicki Minaj", "Drake"] },
    { "title": "Super Bass", "artists": ["Nicki Minaj"] },
    { "title": "Did It On'em", "artists": ["Nicki Minaj"] },
    { "title": "Girls Fall Like Dominoes", "artists": ["Nicki Minaj"] },
    { "title": "Fly", "artists": ["Nicki Minaj", "Rihanna"] },
    { "title": "Starships", "artists": ["Nicki Minaj"] },
    { "title": "Right by My Side", "artists": ["Nicki Minaj", "Chris Brown"] },
    { "title": "Beez in the Trap", "artists": ["Nicki Minaj", "2 Chainz"] },
    { "title": "Pound the Alarm", "artists": ["Nicki Minaj"] },
    { "title": "Va Va Voom", "artists": ["Nicki Minaj"] },
    { "title": "Automatic", "artists": ["Nicki Minaj"] },
    { "title": "The Boys", "artists": ["Nicki Minaj", "Cassie"] },
    { "title": "Freedom", "artists": ["Nicki Minaj"] },
    { "title": "High School", "artists": ["Nicki Minaj", "Lil Wayne"] },
    { "title": "Pills n Potions", "artists": ["Nicki Minaj"] },
    { "title": "Bang Bang", "artists": ["Nicki Minaj", "Jessie J, Ariana Grande"] },
    { "title": "Anaconda", "artists": ["Nicki Minaj"] },
    { "title": "Only", "artists": ["Nicki Minaj", "Drake", "Lil Wayne", "Chris Brown"] },
    { "title": "Bed of Lies", "artists": ["Nicki Minaj", "Skylar Grey"] },
    { "title": "Truffle Butter", "artists": ["Nicki Minaj", "Drake", "Lil Wayne"] },
    { "title": "The Night Is Still Young", "artists": ["Nicki Minaj"] },
    { "title": "Make Love", "artists": ["Nicki Minaj", "Gucci Mane"] },
    { "title": "Changed It", "artists": ["Nicki Minaj", "Lil Wayne"] },
    { "title": "No Frauds", "artists": ["Nicki Minaj", "Drake", "Lil Wayne"] },
    { "title": "Regret in Your Tears", "artists": ["Nicki Minaj"] },
    { "title": "MotorSport", "artists": ["Nicki Minaj", "Migos", "Cardi B"] },
    { "title": "Barbie Tingz", "artists": ["Nicki Minaj"] },
    { "title": "Chun-Li", "artists": ["Nicki Minaj"] },
    { "title": "Bed", "artists": ["Nicki Minaj", "Ariana Grande"] },
    { "title": "Barbie Dreams", "artists": ["Nicki Minaj"] },
    { "title": "Good Form", "artists": ["Nicki Minaj", "Lil Wayne"] },
    { "title": "Megatron", "artists": ["Nicki Minaj"] },
    { "title": "Tusa", "artists": ["Nicki Minaj", "Karol G"] },
    { "title": "Trollz", "artists": ["Nicki Minaj", "6ix9ine"] },
    { "title": "What That Speed Bout!?", "artists": ["Nicki Minaj", "Mike Will Made It", "YoungBoy Never Broke Again"] },
    { "title": "Do We Have a Problem?", "artists": ["Nicki Minaj", "Lil Baby"] },
    { "title": "Bussin", "artists": ["Nicki Minaj", "Lil Baby"] },
    { "title": "Blick Blick", "artists": ["Nicki Minaj", "Coi Leray"] },
    { "title": "We Go Up", "artists": ["Nicki Minaj", "Fivio Foreign"] },
    { "title": "Super Freaky Girl", "artists": ["Nicki Minaj"] },
    { "title": "Love in the Way", "artists": ["Nicki Minaj", "Yung Bleu"] },
    { "title": "Tukoh Taka", "artists": ["Nicki Minaj", "Maluma", "Myriam Fares"] },
    { "title": "Princess Diana", "artists": ["Nicki Minaj", "Ice Spice"] },
    { "title": "Red Ruby da Sleeze", "artists": ["Nicki Minaj"] },
    { "title": "Alone", "artists": ["Nicki Minaj", "Kim Petras"] },
    { "title": "Barbie World", "artists": ["Nicki Minaj", "Ice Spice", "Aqua"] },
    { "title": "Last Time I Saw You", "artists": ["Nicki Minaj"] },
    { "title": "Everybody", "artists": ["Nicki Minaj", "Lil Uzi Vert"] },
    { "title": "FTCU", "artists": ["Nicki Minaj"] },
    { "title": "Big Foot", "artists": ["Nicki Minaj"] },
    //Nicki Minaj as featured artist
    { "title": "Up Out My Face", "artists": ["Nicki Minaj", "Mariah Carey"] },
    { "title": "Knockout", "artists": ["Nicki Minaj", "Lil Wayne"] },
    { "title": "My Chick Bad", "artists": ["Nicki Minaj", "Ludacris"] },
    { "title": "Lil Freak", "artists": ["Nicki Minaj", "USHER"] },
    { "title": "Get It All", "artists": ["Nicki Minaj", "Sean Garrett"] },
    { "title": "Woohoo", "artists": ["Nicki Minaj", "Christina Aguilera"] },
    { "title": "Bottoms Up", "artists": ["Nicki Minaj", "Trey Songz"] },
    { "title": "2012 (It Ain't the End)", "artists": ["Nicki Minaj", "Jay Sean"] },
    { "title": "Letting Go (Dutty Love)", "artists": ["Nicki Minaj", "Sean Kingston"] },
    { "title": "Monster", "artists": ["Nicki Minaj", "Kanye West", "Jay-Z", "Rick Ross", "Bon Iver"] },
    { "title": "I Ain't Thru", "artists": ["Nicki Minaj", "Keyshia Cole"] },
    { "title": "Raining Men", "artists": ["Nicki Minaj", "Rihanna"] },
    { "title": "The Creep", "artists": ["Nicki Minaj", "The Lonely Island"] },
    { "title": "Where Them Girls At", "artists": ["Nicki Minaj", "David Guetta", "Flo Rida"] },
    { "title": "Y.U. Mad", "artists": ["Nicki Minaj", "Birdman", "Lil Wayne"] },
    { "title": "You the Boss", "artists": ["Nicki Minaj", "Rick Ross"] },
    { "title": "Fireball", "artists": ["Nicki Minaj", "Willow"] },
    { "title": "Make Me Proud", "artists": ["Nicki Minaj", "Drake"] },
    { "title": "Turn Me On", "artists": ["Nicki Minaj", "David Guetta"] },
    { "title": "Give Me All Your Luvin'", "artists": ["Nicki Minaj", "Madonna", "M.I.A."] },
    { "title": "Take It to the Head", "artists": ["Nicki Minaj", "DJ Khaled", "Chris Brown", "Rick Ross", "Lil Wayne"] },
    { "title": "Get Low", "artists": ["Nicki Minaj", "Waka Flocka Flame", "Tyga", "Flo Rida"] },
    { "title": "Girl on Fire (Inferno Version)", "artists": ["Nicki Minaj", "Alicia Keys"] },
    { "title": "Out of My Mind", "artists": ["Nicki Minaj", "B.o.B"] },
    { "title": "Beauty and a Beat", "artists": ["Nicki Minaj", "Justin Bieber"] },
    { "title": "Freaks", "artists": ["Nicki Minaj", "French Montana"] },
    { "title": "Tapout", "artists": ["Nicki Minaj", "Rich Gang", "Lil Wayne", "Birdman", "Mack Maine", "Future"] },
    { "title": "Somebody Else", "artists": ["Nicki Minaj", "Mario"] },
    { "title": "I'm Out", "artists": ["Nicki Minaj", "Ciara"] },
    { "title": "Twerk It", "artists": ["Nicki Minaj", "Busta Rhymes"] },
    { "title": "Get Like Me", "artists": ["Nicki Minaj", "Nelly", "Pharrell Williams"] },
    { "title": "Love More", "artists": ["Nicki Minaj", "Chris Brown"] },
    { "title": "I Wanna Be with You", "artists": ["Nicki Minaj", "DJ Khaled", "Future", "Rick Ross"] },
    { "title": "Clappers", "artists": ["Nicki Minaj", "Wale, Juicy J"] },
    { "title": "Lookin Ass", "artists": ["Nicki Minaj", "Young Money"] },
    { "title": "She Came to Give It to You", "artists": ["Nicki Minaj", "USHER"] },
    { "title": "Low", "artists": ["Nicki Minaj", "Juicy J", "Lil Bibby", "Young Thug"] },
    { "title": "Touchin, Lovin", "artists": ["Nicki Minaj", "Trey Songz"] },
    { "title": "Throw Sum Mo", "artists": ["Nicki Minaj", "Rae Sremmurd", "Young Thug"] },
    { "title": "Hey Mama", "artists": ["Nicki Minaj", "David Guetta", "Bebe Rexha", "Afrojack"] },
    { "title": "Bitch I'm Madonna", "artists": ["Nicki Minaj", "Madonna"] },
    { "title": "All Eyes on You", "artists": ["Nicki Minaj", "Meek Mill", "Chris Brown"] },
    { "title": "Back Together", "artists": ["Nicki Minaj", "Robin Thicke"] },
    { "title": "No Broken Hearts", "artists": ["Nicki Minaj", "Bebe Rexha"] },
    { "title": "Don't Hurt Me", "artists": ["Nicki Minaj", "DJ Mustard", "Jeremih"] },
    { "title": "Do You Mind", "artists": ["Nicki Minaj", "DJ Khaled", "Chris Brown", "August Alsina", "Jeremih", "Future", "Rick Ross"] },
    { "title": "Side to Side", "artists": ["Nicki Minaj", "Ariana Grande"] },
    { "title": "Run Up", "artists": ["Nicki Minaj", "Major Lazer", "PartyNextDoor"] },
    { "title": "Swalla", "artists": ["Nicki Minaj", "Jason Derulo", "Ty Dolla Sign"] },
    { "title": "Light My Body Up", "artists": ["Nicki Minaj", "David Guetta", "Lil Wayne"] },
    { "title": "Kissing Strangers", "artists": ["Nicki Minaj", "DNCE"] },
    { "title": "Swish Swish", "artists": ["Nicki Minaj", "Katy Perry"] },
    { "title": "Rake It Up", "artists": ["Nicki Minaj", "Yo Gotti, Mike Will Made It"] },
    { "title": "You da Baddest", "artists": ["Nicki Minaj", "Future"] },
    { "title": "You Already Know", "artists": ["Nicki Minaj", "Fergie"] },
    { "title": "Ball for Me", "artists": ["Nicki Minaj", "Post Malone"] },
    { "title": "Big Bank", "artists": ["Nicki Minaj", "YG", "2 Chainz", "Big Sean"] },
    { "title": "Fefe", "artists": ["Nicki Minaj", "6ix9ine", "Murda Beatz"] },
    { "title": "Goodbye", "artists": ["Nicki Minaj", "Jason Derulo", "David Guetta", "Willy William"] },
    { "title": "Idol", "artists": ["Nicki Minaj", "BTS"] },
    { "title": "Woman Like Me", "artists": ["Nicki Minaj", "Little Mix"] },
    { "title": "Dip", "artists": ["Nicki Minaj", "Tyga"] },
    { "title": "No Candle No Light", "artists": ["Nicki Minaj", "Zayn"] },
    { "title": "Dumb Blonde", "artists": ["Nicki Minaj", "Avril Lavigne"] },
    { "title": "Wobble Up", "artists": ["Nicki Minaj", "Chris Brown", "G-Eazy"] },
    { "title": "BAPS", "artists": ["Nicki Minaj", "Trina"] },
    { "title": "Hot Girl Summer", "artists": ["Nicki Minaj", "Megan Thee Stallion", "Ty Dolla Sign"] },
    { "title": "Ya Lil", "artists": ["Nicki Minaj", "Ramage"] },
    { "title": "Nice to Meet Ya", "artists": ["Nicki Minaj", "Meghan Trainor"] },
    { "title": "Move Ya Hips", "artists": ["Nicki Minaj", "ASAP Ferg", "MadeinTYO"] },
    { "title": "Expensive", "artists": ["Nicki Minaj", "Ty Dolla Sign"] },
    { "title": "Oh My Gawd", "artists": ["Nicki Minaj", "Mr Eazi", "Major Lazer", "K4mo"] },
    { "title": "Boyz", "artists": ["Nicki Minaj", "Jesy Nelson"] },
    { "title": "WTF", "artists": ["Nicki Minaj", "YoungBoy Never Broke Again"] },
    { "title": "Pound Town 2", "artists": ["Nicki Minaj", "Sexyy Red", "Tay Keith"] },
    { "title": "Endless Fashion", "artists": ["Nicki Minaj", "Lil Uzi Vert"] },
    //Promotional singles

    //Other charted songs

    //Guest appearances

    //Beyonce - https://en.wikipedia.org/wiki/Beyonc%C3%A9_singles_discography
    //Beyonce as lead artist
    { "title": "Work It Out", "artists": ["Beyonce"] },
    { "title": "Crazy in Love", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Baby Boy", "artists": ["Beyonce", "Sean Paul"] },
    { "title": "Fighting Temptation", "artists": ["Beyonce", "Missy Elliott", "MC Lyte", "Free"] },
    { "title": "Me, Myself and I", "artists": ["Beyonce"] },
    { "title": "Summertime", "artists": ["Beyonce", "P. Diddy"] },
    { "title": "Naughty Girl", "artists": ["Beyonce"] },
    { "title": "The Closer I Get to You", "artists": ["Beyonce", "Luther Vandross"] },
    { "title": "Wishing on a Star", "artists": ["Beyonce"] },
    { "title": "Check on It", "artists": ["Beyonce", "Bun B", "Slim Thug"] },
    { "title": "Déjà Vu", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Ring the Alarm", "artists": ["Beyonce"] },
    { "title": "Irreplaceable", "artists": ["Beyonce"] },
    { "title": "Listen", "artists": ["Beyonce"] },
    { "title": "Beautiful Liar", "artists": ["Beyonce", "Shakira"] },
    { "title": "Get Me Bodied", "artists": ["Beyonce"] },
    { "title": "Green Light", "artists": ["Beyonce"] },
    { "title": "Until the End of Time", "artists": ["Beyonce", "Justin Timberlake"] },
    { "title": "If I Were a Boy", "artists": ["Beyonce"] },
    { "title": "Single Ladies (Put a Ring on It)", "artists": ["Beyonce"] },
    { "title": "At Last", "artists": ["Beyonce"] },
    { "title": "Diva", "artists": ["Beyonce"] },
    { "title": "Halo", "artists": ["Beyonce"] },
    { "title": "Ego", "artists": ["Beyonce"] },
    { "title": "Sweet Dreams", "artists": ["Beyonce"] },
    { "title": "Broken-Hearted Girl", "artists": ["Beyonce"] },
    { "title": "Video Phone", "artists": ["Beyonce", "Lady Gaga"] },
    { "title": "Why Don't You Love Me", "artists": ["Beyonce"] },
    { "title": "Run the World (Girls)", "artists": ["Beyonce"] },
    { "title": "Best Thing I Never Had", "artists": ["Beyonce"] },
    { "title": "Party", "artists": ["Beyonce", "André 3000"] },
    { "title": "Love on Top", "artists": ["Beyonce"] },
    { "title": "Countdown", "artists": ["Beyonce"] },
    { "title": "I Care", "artists": ["Beyonce"] },
    { "title": "End of Time", "artists": ["Beyonce"] },
    { "title": "XO", "artists": ["Beyonce"] },
    { "title": "Drunk in Love", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Partition", "artists": ["Beyonce"] },
    { "title": "Pretty Hurts", "artists": ["Beyonce"] },
    { "title": "Flawless", "artists": ["Beyonce", "Chimamanda Ngozi Adichie"] },
    { "title": "7/11", "artists": ["Beyonce"] },
    { "title": "Ring Off", "artists": ["Beyonce"] },
    { "title": "Formation", "artists": ["Beyonce"] },
    { "title": "Sorry", "artists": ["Beyonce"] },
    { "title": "Hold Up", "artists": ["Beyonce"] },
    { "title": "Freedom", "artists": ["Beyonce", "Kendrick Lamar"] },
    { "title": "All Night", "artists": ["Beyonce"] },
    { "title": "Perfect Duet", "artists": ["Beyonce", "Ed Sheeran"] },
    { "title": "Spirit", "artists": ["Beyonce"] },
    { "title": "Brown Skin Girl", "artists": ["Beyonce", "Saint Jhn", "Wizkid", "Blue Ivy Carter"] },
    { "title": "Black Parade", "artists": ["Beyonce"] },
    { "title": "Be Alive", "artists": ["Beyonce"] },
    { "title": "Break My Soul", "artists": ["Beyonce"] },
    { "title": "Cuff It", "artists": ["Beyonce"] },
    { "title": "America Has a Problem", "artists": ["Beyonce", "Kendrick Lamar"] },
    { "title": "Virgo's Groove", "artists": ["Beyonce"] },
    { "title": "Delresto (Echoes)", "artists": ["Beyonce", "Travis Scott"] },
    { "title": "My House", "artists": ["Beyonce"] },
    { "title": "Texas Hold 'Em", "artists": ["Beyonce"] },
    { "title": "16 Carriages", "artists": ["Beyonce"] },
    //Beyonce as featured artist
    { "title": "I Got That", "artists": ["Beyonce", "Amil"] },
    { "title": "'03 Bonnie & Clyde", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Hollywood", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Love in This Club Part II", "artists": ["Beyonce", "USHER", "Lil Wayne"] },
    { "title": "Put It in a Love Song", "artists": ["Beyonce", "Alicia Keys"] },
    { "title": "Telephone", "artists": ["Beyonce", "Lady Gaga"] },
    { "title": "Lift Off", "artists": ["Beyonce", "Jay-Z", "Kanye West"] },
    { "title": "Part II (On the Run)", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Say Yes", "artists": ["Beyonce", "Michelle Williams", "Kelly Rowland"] },
    { "title": "Runnin' (Lose It All)", "artists": ["Beyonce", "Naughty Boy", "Arrow Benjamin"] },
    { "title": "Shining", "artists": ["Beyonce", "DJ Khaled", "Jay-Z"] },
    { "title": "Walk on Water", "artists": ["Beyonce", "Eminem"] },
    { "title": "Family Feud", "artists": ["Beyonce", "Jay-Z"] },
    { "title": "Top Off", "artists": ["Beyonce", "DJ Khaled", "Jay-Z", "Future"] },
    { "title": "Make Me Say It Again, Girl", "artists": ["Beyonce", "Ronald Isley", "The Isley Brothers"] },
    //Promotional singles

    //Charity singles

    //Other charted and certified songs

    //Justin Bieber - https://en.wikipedia.org/wiki/Justin_Bieber_discography
    //Justin Bieber as lead artist
    { "title": "One Time", "artists": ["Justin Bieber"] },
    { "title": "One Less Lonely Girl", "artists": ["Justin Bieber"] },
    { "title": "Baby", "artists": ["Justin Bieber", "Ludacris"] },
    { "title": "Eenie Meenie", "artists": ["Justin Bieber", "Sean Kingston"] },
    { "title": "Somebody to Love", "artists": ["Justin Bieber", "USHER"] },
    { "title": "U Smile", "artists": ["Justin Bieber"] },
    { "title": "Never Say Never", "artists": ["Justin Bieber", "Jaden Smith"] },
    { "title": "Pray", "artists": ["Justin Bieber"] },
    { "title": "Mistletoe", "artists": ["Justin Bieber"] },
    { "title": "Boyfriend", "artists": ["Justin Bieber"] },
    { "title": "As Long as You Love Me", "artists": ["Justin Bieber", "Big Sean"] },
    { "title": "Beauty and a Beat", "artists": ["Justin Bieber", "Nicki Minaj"] },
    { "title": "Right Here", "artists": ["Justin Bieber", "Drake"] },
    { "title": "All Around the World", "artists": ["Justin Bieber", "Ludacris"] },
    { "title": "Heartbreaker", "artists": ["Justin Bieber"] },
    { "title": "All That Matters", "artists": ["Justin Bieber"] },
    { "title": "Hold Tight", "artists": ["Justin Bieber"] },
    { "title": "Wait for a Minute", "artists": ["Justin Bieber", "Tyga"] },
    { "title": "Recovery", "artists": ["Justin Bieber"] },
    { "title": "Bad Day", "artists": ["Justin Bieber"] },
    { "title": "All Bad", "artists": ["Justin Bieber"] },
    { "title": "PYD", "artists": ["Justin Bieber", "R. Kelly"] },
    { "title": "Roller Coaster", "artists": ["Justin Bieber"] },
    { "title": "Change Me", "artists": ["Justin Bieber"] },
    { "title": "Confident", "artists": ["Justin Bieber", "Chance the Rapper"] },
    { "title": "Home to Mama", "artists": ["Justin Bieber", "Cody Simpson"] },
    { "title": "Where Are Ü Now", "artists": ["Justin Bieber", "Jack Ü"] },
    { "title": "What Do You Mean?", "artists": ["Justin Bieber"] },
    { "title": "Sorry", "artists": ["Justin Bieber"] },
    { "title": "Love Yourself", "artists": ["Justin Bieber"] },
    { "title": "Company", "artists": ["Justin Bieber"] },
    { "title": "Friends", "artists": ["Justin Bieber", "BloodPop"] },
    { "title": "I Don't Care", "artists": ["Justin Bieber", "Ed Sheeran"] },
    { "title": "10,000 Hours", "artists": ["Justin Bieber", "Dan + Shay"] },
    { "title": "Yummy", "artists": ["Justin Bieber"] },
    { "title": "Intentions", "artists": ["Justin Bieber", "Quavo"] },
    { "title": "Stuck with U", "artists": ["Justin Bieber", "Ariana Grande"] },
    { "title": "Holy", "artists": ["Justin Bieber", "Chance the Rapper"] },
    { "title": "Lonely", "artists": ["Justin Bieber", "Benny Blanco"] },
    { "title": "Monster", "artists": ["Justin Bieber", "Shawn Mendes"] },
    { "title": "Anyone", "artists": ["Justin Bieber"] },
    { "title": "Hold On", "artists": ["Justin Bieber"] },
    { "title": "Peaches", "artists": ["Justin Bieber", "Daniel Caesar", "Giveon"] },
    { "title": "Stay", "artists": ["Justin Bieber", "the Kid Laroi"] },
    { "title": "Don't Go", "artists": ["Justin Bieber", "Skrillex", "Don Toliver"] },
    { "title": "Ghost", "artists": ["Justin Bieber"] },
    { "title": "Rockin' Around the Christmas Tree", "artists": ["Justin Bieber"] },
    { "title": "Wandered to LA", "artists": ["Justin Bieber", "Juice Wrld"] },
    { "title": "Attention", "artists": ["Justin Bieber", "Omah Lay"] },
    { "title": "Honest", "artists": ["Justin Bieber", "Don Toliver"] },
    //Justin Bieber as featured artist
    { "title": "Next to You", "artists": ["Justin Bieber", "Chris Brown"] },
    { "title": "Live My Life", "artists": ["Justin Bieber", "Far East Movement"] },
    { "title": "#thatPower", "artists": ["Justin Bieber", "will.i.am"] },
    { "title": "Lolly", "artists": ["Justin Bieber", "Maejor Ali", "Juicy J"] },
    { "title": "Cold Water", "artists": ["Justin Bieber", "Major Lazer", "MØ"] },
    { "title": "Let Me Love You", "artists": ["Justin Bieber", "DJ Snake"] },
    { "title": "Deja Vu", "artists": ["Justin Bieber", "Post Malone"] },
    { "title": "I'm the One", "artists": ["Justin Bieber", "DJ Khaled", "Quavo", "Chance the Rapper", "Lil Wayne"] },
    { "title": "2U", "artists": ["Justin Bieber", "David, Guetta"] },
    { "title": "Hard 2 Face Reality", "artists": ["Justin Bieber", "Poo Bear", "Jay Electronica"] },
    { "title": "No Brainer", "artists": ["Justin Bieber", "DJ Khaled", "Chance the Rapper", "Quavo"] },
    { "title": "Love Thru the Computer", "artists": ["Justin Bieber", "Gucci Mane"] },
    { "title": "Let It Go", "artists": ["Justin Bieber", "DJ Khaled", "21 Savage"] },
    { "title": "Lonely Christmas", "artists": ["Justin Bieber", "Bryson Tiller", "Poo Bear"] },
    { "title": "Up at Night", "artists": ["Justin Bieber", "Kehlani"] },
    { "title": "Private Landing", "artists": ["Justin Bieber", "Don Toliver", "Future"] },
    //Promotional singles

    //Other charted and certified songs

    //Guest appearances

    //Justin Timberlake - https://en.wikipedia.org/wiki/Justin_Timberlake_discography
    //Justin Timberlake as lead artist
    { "title": "Like I Love You", "artists": ["Justin Timberlake"] },
    { "title": "Cry Me a River", "artists": ["Justin Timberlake"] },
    { "title": "Rock Your Body", "artists": ["Justin Timberlake"] },
    { "title": "Señorita", "artists": ["Justin Timberlake"] },
    { "title": "Still on My Brain", "artists": ["Justin Timberlake"] },
    { "title": "I'm Lovin' It", "artists": ["Justin Timberlake"] },
    { "title": "SexyBack", "artists": ["Justin Timberlake"] },
    { "title": "My Love", "artists": ["Justin Timberlake", "T.I."] },
    { "title": "What Goes Around... Comes Around", "artists": ["Justin Timberlake"] },
    { "title": "Summer Love", "artists": ["Justin Timberlake"] },
    { "title": "LoveStoned", "artists": ["Justin Timberlake"] },
    { "title": "Until the End of Time", "artists": ["Justin Timberlake", "Beyonce"] },
    { "title": "The Only Promise That Remains", "artists": ["Justin Timberlake", "Reba McEntire"] },
    { "title": "Follow My Lead", "artists": ["Justin Timberlake", "Esmée Denters"] },
    { "title": "Hallelujah", "artists": ["Justin Timberlake", "Matt Morris", "Charlie Sexton"] },
    { "title": "Suit & Tie", "artists": ["Justin Timberlake", "Jay-Z"] },
    { "title": "Mirrors", "artists": ["Justin Timberlake"] },
    { "title": "Tunnel Vision", "artists": ["Justin Timberlake"] },
    { "title": "Take Back the Night", "artists": ["Justin Timberlake"] },
    { "title": "TKO", "artists": ["Justin Timberlake"] },
    { "title": "Not a Bad Thing", "artists": ["Justin Timberlake"] },
    { "title": "Love Never Felt So Good", "artists": ["Justin Timberlake", "Michael, Jackson"] },
    { "title": "Drink You Away", "artists": ["Justin Timberlake"] },
    { "title": "Can't Stop the Feeling!", "artists": ["Justin Timberlake"] },
    { "title": "Filthy", "artists": ["Justin Timberlake"] },
    { "title": "Supplies", "artists": ["Justin Timberlake"] },
    { "title": "Say Something", "artists": ["Justin Timberlake", "Chris Stapleton"] },
    { "title": "Man of the Woods", "artists": ["Justin Timberlake"] },
    { "title": "SoulMate", "artists": ["Justin Timberlake"] },
    { "title": "The Other Side", "artists": ["Justin Timberlake", "SZA"] },
    { "title": "Stay with Me", "artists": ["Justin Timberlake", "Calvin Harris", " Halsey", "Pharrell Williams"] },
    { "title": "Sin Fin", "artists": ["Justin Timberlake", "Romeo", "Santos"] },
    { "title": "Keep Going Up", "artists": ["Justin Timberlake", "Timbaland", "Nelly Furtado"] },
    { "title": "Selfish", "artists": ["Justin Timberlake"] },
    //Justin Timberlake as featured artist
    { "title": "Work It", "artists": ["Justin Timberlake", "Nelly"] },
    { "title": "Signs", "artists": ["Justin Timberlake", "Snoop Dogg", "Charlie Wilson"] },
    { "title": "Dick in a Box", "artists": ["Justin Timberlake", "The Lonely Island"] },
    { "title": "Give It to Me", "artists": ["Justin Timberlake", "Timbaland", "Nelly Furtado"] },
    { "title": "Ayo Technology", "artists": ["Justin Timberlake", "50 Cent"] },
    { "title": "4 Minutes", "artists": ["Justin Timberlake", "Madonna", "Timbaland"] },
    { "title": "Dead and Gone", "artists": ["Justin Timberlake", "T.I."] },
    { "title": "Love Sex Magic", "artists": ["Justin Timberlake", "Ciara"] },
    { "title": "Carry Out", "artists": ["Justin Timberlake", "Timbaland"] },
    { "title": "Winner", "artists": ["Justin Timberlake", "Jamie Foxx", "T.I."] },
    { "title": "Love Dealer", "artists": ["Justin Timberlake", "Esmée Denters"] },
    { "title": "Motherlover", "artists": ["Justin Timberlake", "The Lonely Island"] },
    { "title": "3-Way (The Golden Rule)", "artists": ["Justin Timberlake", "The Lonely Island", "Lady Gaga"] },
    { "title": "Role Model", "artists": ["Justin Timberlake", "FreeSol"] },
    { "title": "Fascinated", "artists": ["Justin Timberlake", "FreeSol", "Timbaland"] },
    { "title": "Holy Grail", "artists": ["Justin Timberlake", "Jay-Z"] },
    { "title": "Believe", "artists": ["Justin Timberlake", "Meek Mill"] },
    { "title": "Better Days", "artists": ["Justin Timberlake", "Ant Clemons"] },
    //Promotional singles

    //Other charted songs

    //Other appearances

    //Flo Rida - https://en.wikipedia.org/wiki/Flo_Rida_discography
    //Flo Rida as lead artist
    { "title": "Low", "artists": ["Flo Rida", "T-Pain"] },
    { "title": "Elevator", "artists": ["Flo Rida", "Timbaland"] },
    { "title": "In the Ayer", "artists": ["Flo Rida", "will.i.am"] },
    { "title": "Right Round", "artists": ["Flo Rida", "Kesha"] },
    { "title": "Shone", "artists": ["Flo Rida", "Pleasure P"] },
    { "title": "Sugar", "artists": ["Flo Rida", "Wynter Gordon"] },
    { "title": "Jump", "artists": ["Flo Rida", "Nelly Furtado"] },
    { "title": "Be on You", "artists": ["Flo Rida", "Ne-Yo"] },
    { "title": "Available", "artists": ["Flo Rida", "Akon"] },
    { "title": "Club Can't Handle Me", "artists": ["Flo Rida", "David Guetta"] },
    { "title": "Turn Around (5, 4, 3, 2, 1)", "artists": ["Flo Rida"] },
    { "title": "Who Dat Girl", "artists": ["Flo Rida", "Akon"] },
    { "title": "Good Feeling", "artists": ["Flo Rida"] },
    { "title": "Wild Ones", "artists": ["Flo Rida", "Sia"] },
    { "title": "Whistle", "artists": ["Flo Rida"] },
    { "title": "I Cry", "artists": ["Flo Rida"] },
    { "title": "Let It Roll", "artists": ["Flo Rida"] },
    { "title": "Can't Believe It", "artists": ["Flo Rida", "Pitbull"] },
    { "title": "How I Feel", "artists": ["Flo Rida"] },
    { "title": "G.D.F.R.", "artists": ["Flo Rida", "Sage the Gemini", "Lookas"] },
    { "title": "I Don't Like It, I Love It", "artists": ["Flo Rida", "Robin Thicke", "Verdine White"] },
    { "title": "My House", "artists": ["Flo Rida"] },
    { "title": "Hello Friday", "artists": ["Flo Rida", "Jason Derulo"] },
    { "title": "Zillionaire", "artists": ["Flo Rida"] },
    { "title": "Hola", "artists": ["Flo Rida", "Maluma"] },
    { "title": "Dancer", "artists": ["Flo Rida"] },
    { "title": "Sweet Sensation", "artists": ["Flo Rida"] },
    { "title": "In My Mind, Part 3", "artists": ["Flo Rida", "Georgi Kay"] },
    { "title": "Snack", "artists": ["Flo Rida", "E-40", "Sage the Gemini"] },
    { "title": "Summer's Not Ready", "artists": ["Flo Rida", "INNA", "Timmy Trumpet"] },
    { "title": "Wait", "artists": ["Flo Rida"] },
    { "title": "What A Night", "artists": ["Flo Rida"] },
    { "title": "No Bad Days", "artists": ["Flo Rida"] },
    { "title": "High Heels", "artists": ["Flo Rida", "Walker Hayes)"] },
    { "title": "Good Girls on Vacation", "artists": ["Flo Rida"] },
    { "title": "Feels Right (I Love It)", "artists": ["Flo Rida", "Brian Kelley"] },

    //Pitbull - https://en.wikipedia.org/wiki/Pitbull_discography
    //Pitbull as lead artist
    { title: "Culo", artists: ["Pitbull", "Lil Jon"] },
    { title: "That's Nasty", artists: ["Pitbull", "Lil Jon", "Fat Joe"] },
    { title: "Back Up", artists: ["Pitbull"] },
    { title: "Toma", artists: ["Pitbull", "Lil Jon"] },
    { title: "Dammit Man", artists: ["Pitbull", "Piccallo"] },
    { title: "Everybody Get Up[65]", artists: ["Pitbull", "Pretty Ricky"] },
    { title: "Bojangles", artists: ["Pitbull"] },
    { title: "Ay Chico (Lengua Afuera)", artists: ["Pitbull"] },
    { title: "Dime (Remix)", artists: ["Pitbull", "Frankie J", "Ken-Y"] }, //
    { title: "Be Quiet", artists: ["Pitbull"] },
    { title: "Go Girl", artists: ["Pitbull", "Trina", "and", "Young", "Boss"] },
    { title: "The Anthem", artists: ["Pitbull", "Lil", "Jon"] },
    { title: "Sticky Icky", artists: ["Pitbull", "Jim", "Jones"] },
    { title: "Secret Admirer", artists: ["Pitbull", "Lloyd"] },
    { title: "Krazy", artists: ["Pitbull", "Lil", "Jon"] },
    { title: "I Know You Want Me (Calle Ocho)", artists: ["Pitbull"] },
    { title: "Hotel Room Service", artists: ["Pitbull"] },
    { title: "Shut It Down", artists: ["Pitbull", "Akon"] },
    { title: "Watagatapitusberry", artists: ["Pitbull", "Sensato,", "El", "Cata,", "Black", "Point", "and", "Lil", "Jon"] },
    { title: "Maldito Alcohol", artists: ["Pitbull", "vs.", "Afrojack"] },
    { title: "Bon, Bon", artists: ["Pitbull"] },
    { title: "Hey Baby (Drop It to the Floor)", artists: ["Pitbull", "T-Pain"] },
    { title: "Tu Cuerpo", artists: ["Pitbull", "Jencarlos"] },
    { title: "Give Me Everything", artists: ["Pitbull", "Ne-Yo,", "Afrojack", "and", "Nayer"] },
    { title: "Rain Over Me", artists: ["Pitbull", "Marc", "Anthony"] },
    { title: "International Love", artists: ["Pitbull", "Chris", "Brown"] },
    { title: "I Like (The Remix)", artists: ["Pitbull", "Enrique", "Iglesias", "and", "Afrojack"] },
    { title: "Back in Time", artists: ["Pitbull"] },
    { title: "Get It Started", artists: ["Pitbull", "Shakira"] },
    { title: "Don't Stop the Party", artists: ["Pitbull", "TJR"] },
    { title: "Feel This Moment", artists: ["Pitbull", "Christina", "Aguilera"] },
    { title: "Outta Nowhere", artists: ["Pitbull", "Danny", "Mercer"] },
    { title: "Timber", artists: ["Pitbull", "Kesha"] },
    { title: "Wild Wild Love", artists: ["Pitbull", "G.R.L."] },
    { title: "We Are One (Ole Ola)", artists: ["Pitbull", "Jennifer", "Lopez", "and", "Claudia", "Leitte"] },
    { title: "Fireball", artists: ["Pitbull", "John", "Ryan"] },
    { title: "Como Yo Le Doy", artists: ["Pitbull", "Don", "Miguelo"] },
    { title: "El Taxi", artists: ["Pitbull", "Osmani", "García", "and", "Sensato"] },
    { title: "Celebrate", artists: ["Pitbull"] },
    { title: "Time of Our Lives", artists: ["Pitbull", "Ne-Yo"] },
    { title: "Piensas (Dile la Verdad)[99]", artists: ["Pitbull", "Gente", "de", "Zona"] },
    { title: "Fun", artists: ["Pitbull", "Chris", "Brown"] },
    { title: "Baddest Girl in Town", artists: ["Pitbull", "Mohombi", "and", "Wisin"] },
    { title: "Drive You Crazy", artists: ["Pitbull", "Jason", "Derulo", "and", "Juicy", "J"] },
    { title: "Messin' Around", artists: ["Pitbull", "Enrique", "Iglesias"] },
    { title: "Greenlight", artists: ["Pitbull", "Flo", "Rida", "and", "LunchMoney", "Lewis)"] },
    { title: "Options", artists: ["Pitbull", "Stephen", "Marley"] },
    { title: "Hey Ma", artists: ["Pitbull", "J", "Balvin", "Camila", "Cabello"] },
    { title: "Better On Me", artists: ["Pitbull", "Ty", "Dolla", "Sign"] },
    { title: "Por Favor", artists: ["Pitbull", "Fifth", "Harmony"] },
    { title: "Jungle", artists: ["Pitbull", "Stereotypes", "E-40", "and", "Abraham", "Mateo)"] },
    { title: "Amore", artists: ["Pitbull", "Leona", "Lewis)"] },
    { title: "So Sorry", artists: ["Pitbull"] },
    { title: "Dame Tu Cosita", artists: ["Pitbull", "El", "Chombo", "and", "Karol", "G", "Cutty", "Ranks"] },
    { title: "Quiero Saber", artists: ["Pitbull", "Prince", "Royce", "and", "Ludacris"] },
    { title: "Ocean to Ocean", artists: ["Pitbull", "Rhea"] },
    { title: "No Lo Trates", artists: ["Pitbull", "Natti", "Natasha", "and", "Daddy", "Yankee"] },
    { title: "3 to Tango", artists: ["Pitbull"] },
    { title: "Me Quedaré Contigo", artists: ["Pitbull", "Ne-Yo", "Lenier", "and", "El", "Micha"] },
    { title: "Get Ready[113]", artists: ["Pitbull", "Blake", "Shelton"] },
    { title: "I Believe That We Will Win (World Anthem)[114]", artists: ["Pitbull"] },
    { title: "Mueve La Cintura[115]", artists: ["Pitbull", "Tito", "El", "Bambino", "and", "Guru", "Randhawa"] },
    { title: "Mala (Remix)[116]", artists: ["Pitbull", "Becky", "G", "and", "De", "La", "Ghetto"] },
    { title: "Moviéndolo (Remix)[117]", artists: ["Pitbull", "Wisin", "&", "Yandel", "and", "El", "Alfa"] },
    { title: "Que Rica (Tocame)[118]", artists: ["Pitbull", "Sak", "Noel", "and", "Salvi"] },
    { title: "Se La Vi[119]", artists: ["Pitbull", "IAmChino", "and", "Papayo"] },
    { title: "Winning[120]", artists: ["Pitbull", "Yomil", "y", "El", "Dany"] },
    { title: "Tell Me Again[121]", artists: ["Pitbull", "Prince", "Royce", "and", "Ludacris"] },
    { title: "Cantare[122]", artists: ["Pitbull", "Lenier"] },
    { title: "Ten Cuidado[123]", artists: ["Pitbull", "Farruko", "and", "IAmChino", "El", "Alfa", "and", "Omar", "Courtz"] },
    { title: "I Feel Good[124]", artists: ["Pitbull", "Anthony", "Watts", "and", "DJWS"] },
    { title: "Can't Stop Us Now[125]", artists: ["Pitbull", "Zac", "Brown"] },
    { title: "Café Con Leche[126]", artists: ["Pitbull"] },
    { title: "Party of a Lifetime[127]", artists: ["Pitbull", "Play-N-Skillz"] },
    { title: "Mamasota[128]", artists: ["Pitbull"] },
    { title: "Right or Wrong (Hypnosis)[129]", artists: ["Pitbull", "AYYBO", "and", "ero808"] },
    { title: "Mami[130]", artists: ["Pitbull"] },
    { title: "Me Pone Mal[131]", artists: ["Pitbull", "Omar", "Courtz"] },
    { title: "Jumpin[132]", artists: ["Pitbull", "Lil", "Jon"] },
    { title: "Freak 54 (Freak Out)[133]", artists: ["Pitbull", "Nile", "Rodgers"] },
    { title: "2 the Moon", artists: ["Pitbull", "Ne-Yo", "and", "Afrojack"] },
    { title: "Now or Never", artists: ["Pitbull", "Bon", "Jovi)[134"] },
    { title: "Bhool Bhulaiyaa 3 Title Track", artists: ["Pitbull", "Diljit", "Dosanjh", "and", "Neeraj", "Shridhar)[135"] },
    { title: "Tamo Bien", artists: ["Pitbull", "Enrique", "Iglesias", "and", "IAmChino"] },
    //Pitbull as featured artist
    { title: "Shake", artists: ["Pitbull", "Ying", "Yang", "Twins"] },
    { title: "Hit the Floor", artists: ["Pitbull", "Twista"] },
    { title: "Kamasutra[137]", artists: ["Pitbull", "Adassa"] },
    { title: "Get Freaky[138]", artists: ["Pitbull", "Play-N-Skillz"] },
    { title: "Holla at Me", artists: ["Pitbull", "DJ", "Khaled", "Lil", "Wayne,", "Paul", "Wall,", "Fat", "Joe,", "Rick", "Ross", "and"] },
    { title: "Born-N-Raised[139]", artists: ["Pitbull", "DJ", "Khaled", "Trick", "Daddy,", "Rick", "Ross", "and"] },
    { title: "Crazy", artists: ["Pitbull", "Lumidee"] },
    { title: "Mi Alma Se Muere[140]", artists: ["Pitbull", "Fuego", "Omega", "and"] },
    { title: "Move Shake Drop", artists: ["Pitbull", "DJ", "Laz", "Flo", "Rida,", "Casely", "and"] },
    { title: "Swing (Remix)[141]", artists: ["Pitbull", "Savage"] },
    { title: "Feel It[142]", artists: ["Pitbull", "DJ", "Felli", "Fel", "T-Pain,", "Sean", "Paul,", "Flo", "Rida", "and"] },
    { title: "Shooting Star (Party Rock Remix)", artists: ["Pitbull", "David", "Rush", "Pitbull,", "Kevin", "Rudolf", "and", "LMFAO"] },
    { title: "Take Me on the Floor (Remix)", artists: ["Pitbull", "The", "Veronicas"] },
    { title: "Now I'm That Bitch", artists: ["Pitbull", "Livvi", "Franc"] },
    { title: "Outta Control", artists: ["Pitbull", "Baby", "Bash"] },
    { title: "Patron Tequila (Vanguards Remix)[143]", artists: ["Pitbull", "Paradiso", "Girls", "and", "Lil", "Jon"] },
    { title: "Future Love", artists: ["Pitbull", "Kristina", "DeBarge"] },
    { title: "Now You See It (Shake That Ass)[144]", artists: ["Pitbull", "Honorebel", "and", "Jump", "Smokers"] },
    { title: "Ni Rosas Ni Juguetes (Mr. 305 Remix)[145]", artists: ["Pitbull", "Paulina", "Rubio"] },
    { title: "Egoísta[146]", artists: ["Pitbull", "Belinda"] },
    { title: "Armada Latina", artists: ["Pitbull", "Cypress", "Hill", "Marc", "Anthony", "and"] },
    { title: "All Night Long", artists: ["Pitbull", "Alexandra", "Burke"] },
    { title: "I Like It", artists: ["Pitbull", "Enrique", "Iglesias"] },
    { title: "I Wanna[151]", artists: ["Pitbull", "Honorebel"] },
    { title: "Get to Know Me Better[152]", artists: ["Pitbull", "Naughty", "by", "Nature"] },
    { title: "Oye Baby[153]", artists: ["Pitbull", "Nicola", "Fasano"] },
    { title: "DJ Got Us Fallin' in Love", artists: ["Pitbull", "Usher"] },
    { title: "One Thing Leads to Another[156]", artists: ["Pitbull", "Ray", "J"] },
    { title: "On the Floor", artists: ["Pitbull", "Jennifer", "Lopez"] },
    { title: "Rabiosa", artists: ["Pitbull", "Shakira"] },
    { title: "Boomerang[162]", artists: ["Pitbull", "DJ", "Felli", "Fel", "Akon,", "and", "Jermaine", "Dupri"] },
    { title: "Bumpy Ride (Remix)[163]", artists: ["Pitbull", "Mohombi", "and", "Machel", "Montano"] },
    { title: "Fired Up (Fuck the Recession)", artists: ["Pitbull", "Shaggy"] },
    { title: "Suave (Kiss Me)", artists: ["Pitbull", "Nayer", "Mohombi", "and"] },
    { title: "Throw Your Hands Up (Dançar Kuduro)", artists: ["Pitbull", "Qwote", "and", "Lucenzo"] },
    { title: "Pass at Me", artists: ["Pitbull", "Timbaland"] },
    { title: "I Like How It Feels", artists: ["Pitbull", "Enrique", "Iglesias", "and", "The", "WAV.s"] },
    { title: "Bailando Por El Mundo", artists: ["Pitbull", "Juan", "Magan", "and", "El", "Cata"] },
    { title: "U Know It Ain't Love", artists: ["Pitbull", "R.J."] },
    { title: "Crazy People", artists: ["Pitbull", "Sensato", "and", "Sak", "Noel"] },
    { title: "Rock the Boat", artists: ["Pitbull", "Bob", "Sinclar", "Pitbull,", "Dragonfly", "and", "Fatman", "Scoop"] },
    { title: "Raise the Roof[164]", artists: ["Pitbull", "Hampenberg", "and", "Alexander", "Brown", "Pitbull,", "Fatman", "Scoop", "and", "Nabiha"] },
    { title: "Name of Love", artists: ["Pitbull", "Jean-Roch", "and", "Nayer"] },
    { title: "Richest Man[165]", artists: ["Pitbull", "Play-N-Skillz"] },
    { title: "Bedroom", artists: ["Pitbull", "Redd", "and", "Qwote"] },
    { title: "Dance Again", artists: ["Pitbull", "Jennifer", "Lopez"] },
    { title: "There She Goes", artists: ["Pitbull", "Taio", "Cruz"] },
    { title: "Beat on My Drum[168]", artists: ["Pitbull", "Gabry", "Ponte", "and", "Sophia", "Del", "Carmen"] },
    { title: "I'm All Yours", artists: ["Pitbull", "Jay", "Sean"] },
    { title: "Letting Go (Cry Just a Little)", artists: ["Pitbull", "Qwote", "Mr.", "Worldwide"] },
    { title: "Ai Se Eu Te Pego (If I Get Ya) (Mr. Worldwide Remix)[169]", artists: ["Pitbull", "Michel", "Teló"] },
    { title: "Sin Ti (I Don't Want to Miss a Thing)[170]", artists: ["Pitbull", "Dyland", "&", "Lenny", "and", "Beatriz", "Luengo"] },
    { title: "Bad (Afrojack Remix)", artists: ["Pitbull", "Michael", "Jackson"] },
    { title: "Hiya Hiya[171]", artists: ["Pitbull", "Khaled"] },
    { title: "Sexy People (The Fiat Song)", artists: ["Pitbull", "Arianna"] },
    { title: "Spring Love 2013", artists: ["Pitbull", "Stevie", "B"] },
    { title: "Live It Up", artists: ["Pitbull", "Jennifer", "Lopez"] },
    { title: "Chasing Shadows[172]", artists: ["Pitbull", "Jamie", "Drastik", "and", "Havana", "Brown"] },
    { title: "Habibi I Love You", artists: ["Pitbull", "Ahmed", "Chawki"] },
    { title: "Exotic", artists: ["Pitbull", "Priyanka", "Chopra"] },
    { title: "Can't Believe It", artists: ["Pitbull", "Flo", "Rida"] },
    { title: "Sopa de Caracol - Yupi[O]", artists: ["Pitbull", "Elvis", "Crespo"] },
    { title: "Seize the Night[175]", artists: ["Pitbull", "Honorebel"] },
    { title: "FCK[176]", artists: ["Pitbull", "Gary", "Caos", "and", "Snow", "Tha", "Product"] },
    { title: "Get on the Floor (Vamos Dançar)[177]", artists: ["Pitbull", "Carolina", "Márquez", "and", "Dale", "Saunders"] },
    { title: "I'm a Freak", artists: ["Pitbull", "Enrique", "Iglesias"] },
    { title: "I Love You... Te Quiero", artists: ["Pitbull", "Belinda"] },
    { title: "Mmm Yeah", artists: ["Pitbull", "Austin", "Mahone"] },
    { title: "Can't Get Enough[179]", artists: ["Pitbull", "Becky", "G"] },
    { title: "Drink to That All Night (Remix)[180]", artists: ["Pitbull", "Jerrod", "Niemann"] },
    { title: "Good Time", artists: ["Pitbull", "Inna"] },
    { title: "Yo Quiero (Si Tú Te Enamores)[181]", artists: ["Pitbull", "Gente", "de", "Zona"] },
    { title: "Booty", artists: ["Pitbull", "Jennifer", "Lopez"] },
    { title: "Mr. Put It Down", artists: ["Pitbull", "Ricky", "Martin"] },
    { title: "Back It Up", artists: ["Pitbull", "Prince", "Royce", "Jennifer", "Lopez", "and"] },
    { title: "Shake That", artists: ["Pitbull", "Samantha", "Jade"] },
    { title: "Lady", artists: ["Pitbull", "Austin", "Mahone"] },
    { title: "All of the Girls", artists: ["Pitbull", "Cris", "Cab"] },
    { title: "Loca!", artists: ["Pitbull", "Adassa"] },
    { title: "Carnaval", artists: ["Pitbull", "Claudia", "Leitte"] },
    { title: "Move to Miami", artists: ["Pitbull", "Enrique", "Iglesias"] },
    { title: "Goalie Goalie", artists: ["Pitbull", "Arash", "Nyusha,", "and", "Blanco"] },
    { title: "Body On My[183]", artists: ["Pitbull", "Loud", "Luxury", "Brando,", "and", "Nicky", "Jam"] },
    { title: "One Shot - Remix[184]", artists: ["Pitbull", "Bria", "Lee", "Fat", "Joe", "and"] },
    { title: "Yayo[185]", artists: ["Pitbull", "Papayo", "and", "Ky-Mani", "Marley"] },
    { title: "Slowly Slowly[186]", artists: ["Pitbull", "Guru", "Randhawa"] },
    { title: "Tocame[187]", artists: ["Pitbull", "Elettra", "Lamborghini", "and", "ChildsPlay"] },
    { title: "Ay Ay Ay", artists: ["Pitbull", "Kim", "Viera"] },
    { title: "Further Up (Na, Na, Na, Na, Na)", artists: ["Pitbull", "Static", "&", "Ben", "El"] },
    { title: "Suda[188]", artists: ["Pitbull", "Melanie", "Pfirrman", "and", "IAmChino"] },
    { title: "Te Quiero Amar", artists: ["Pitbull", "Akon"] },
    { title: "Te Quiero Baby (I Love You Baby)[189]", artists: ["Pitbull", "Chesca", "and", "Frankie", "Valli"] },
    { title: "Backpack[190]", artists: ["Pitbull", "TAG", "and"] },
    { title: "Borracha (Pero Buena Muchacha)[191]", artists: ["Pitbull", "Vikina,", "and", "IAmChino"] },
    { title: "Voodoo[192]", artists: ["Pitbull", "Mr.", "Mauricio", "Pitbull,", "Jencarlos", "and", "Konshens"] },
    { title: "Give It To Me[193]", artists: ["Pitbull", "IAmChino", "and", "Yomil", "y", "El", "Dany"] },
    { title: "Cosita Linda[194]", artists: ["Pitbull", "Jencarlos", "and"] },
    { title: "Where The Country Girls At[195]", artists: ["Pitbull", "Trace", "Adkins", "Luke", "Bryan", "and"] },
    { title: "Flavor[196]", artists: ["Pitbull", "Jimmie", "Allen,", "and", ".teamwork", "Vikina"] },
    { title: "Discoteca[197]", artists: ["Pitbull", "IAmChino", "and"] },
    { title: "Move To Miami[198]", artists: ["Pitbull", "Enrique", "Iglesias"] },
    { title: "Hot[199]", artists: ["Pitbull", "Daddy", "Yankee"] },
    { title: "USA[200]", artists: ["Pitbull", "Filmore"] },
    { title: "Que Se Joda[201]", artists: ["Pitbull", "Play-N-Skillz", "and", "Lil", "Jon"] },
    { title: "Bandida[202]", artists: ["Pitbull", "IAmChino", "and", "Yandel"] },
    //Promotional singles
    { title: "No Llores", artists: ["Pitbull", "Gloria", "Estefan"] },
    { title: "Fresh Out the Oven", artists: ["Pitbull", "Lola"] },
    { title: "Blanco[204]", artists: ["Pitbull", "Pharrell"] },
    { title: "Pearly Gates[205]", artists: ["Pitbull", "Nayer"] },
    { title: "Game On[206]", artists: ["Pitbull", "TKZee", "and", "Dario", "G"] },
    { title: "Alright", artists: ["Pitbull", "Machel", "Montano"] },
    { title: "Pause", artists: ["Pitbull"] },
    { title: "Turn Around, Pt. 2[207]", artists: ["Pitbull", "Flo", "Rida"] },
    { title: "Shake Señora", artists: ["Pitbull", "T-Pain", "and", "Sean", "Paul"] },
    { title: "Echa Pa'lla (Manos Pa'rriba)", artists: ["Pitbull", "Papayo"] },
    { title: "Free.K", artists: ["Pitbull"] },
    { title: "Freedom[208]", artists: ["Pitbull"] },
    { title: "Bad Man[209]", artists: ["Pitbull", "Robin", "Thicke,", "Joe", "Perry", "and", "Travis", "Barker"] },
    { title: "Mucho Booty[210]", artists: ["Pitbull", "Farruko", "and", "Micha"] },
    { title: "Muévelo Loca Boom Boom[211]", artists: ["Pitbull"] },
    { title: "Free Free Free", artists: ["Pitbull", "Theron", "Theron)[212"] },
    { title: "La Reina De Blanco[213]", artists: ["Pitbull", "Chesca,", "Giorgio", "Moroder", "and", "Raney", "Shockne"] },
    { title: "Cinco de Mayo[214]", artists: ["Pitbull", "Lil", "Jon", "Chesca"] },
    { title: "Takes 3[215] (record pool release only)", artists: ["Pitbull", "Vikina"] },
    { title: "Let's Take A Shot[216]", artists: ["Pitbull", "Vikina"] },
    { title: "Suave[217]", artists: ["Pitbull", "Elvis", "Crespo"] },
    { title: "Lit In The City[218]", artists: ["Pitbull", "T-Pain", "and", "El", "Micha"] },
    { title: "It Takes 3[219]", artists: ["Pitbull", "Vikina"] },

    //Other charted songs

    //Other appearances
];


export default Songs;